# Funding for Pose
#
# This file is read by GitHub to display the "Sponsor" button on the repo.
# When the maintainer enrolls in any of these programs, uncomment the relevant
# line and fill in the username/handle.
#
# See https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
# for the full list of supported platforms.

# github: sarisabban
# open_collective: pose
# patreon: sarisabban
# tidelift: pypi/pose
# custom: ["https://example.com/donate"]
