#!/usr/bin/env python3

import os
import math
import json
import copy
import datetime
import numpy as np
from collections import defaultdict

np.seterr(all='ignore')

class Pose():
	''' Data structure that represents a protein '''
	def __init__(self):
		path, modulename = os.path.split(__file__)
		with open(f'{path}/AminoAcids_N.json') as f: self.AminoAcids=json.load(f)
		self.BB_ATOMS = {'N', '1H', '2H', '3H', 'CA', 'HA', 'C', 'O', 'OXT'}
		self.Masses = {
			'H':1.008,    'He':4.003,   'Li':6.941,   'Be':9.012,
			'B':10.811,   'C':12.011,   'N':14.007,   'O':15.999,
			'F':18.998,   'Ne':20.180,  'Na':22.990,  'Mg':24.305,
			'Al':26.982,  'Si':28.086,  'P':30.974,   'S':32.066,
			'Cl':35.453,  'Ar':39.948,  'K':39.098,   'Ca':40.078,
			'Sc':44.956,  'Ti':47.867,  'V':50.942,   'Cr':51.996,
			'Mn':54.938,  'Fe':55.845,  'Co':58.933,  'Ni':58.693,
			'Cu':63.546,  'Zn':65.38,   'Ga':69.723,  'Ge':72.631,
			'As':74.922,  'Se':78.971,  'Br':79.904,  'Kr':84.798,
			'Rb':84.468,  'Sr':87.62,   'Y':88.906,   'Zr':91.224,
			'Nb':92.906,  'Mo':95.95,   'Tc':98.907,  'Ru':101.07,
			'Rh':102.906, 'Pd':106.42,  'Ag':107.868, 'Cd':112.414,
			'In':114.818, 'Sn':118.711, 'Sb':121.760, 'Te':126.7,
			'I':126.904,  'Xe':131.294, 'Cs':132.905, 'Ba':137.328,
			'La':138.905, 'Ce':140.116, 'Pr':140.908, 'Nd':144.243,
			'Pm':144.913, 'Sm':150.36,  'Eu':151.964, 'Gd':157.25,
			'Tb':158.925, 'Dy':162.500, 'Ho':164.930, 'Er':167.259,
			'Tm':168.934, 'Yb':173.055, 'Lu':174.967, 'Hf':178.49,
			'Ta':180.948, 'W':183.84,   'Re':186.207, 'Os':190.23,
			'Ir':192.217, 'Pt':195.085, 'Au':196.967, 'Hg':200.592,
			'Tl':204.383, 'Pb':207.2,   'Bi':208.980, 'Po':208.982,
			'At':209.987, 'Rn':222.081, 'Fr':223.020, 'Ra':226.025,
			'Ac':227.028, 'Th':232.038, 'Pa':231.036, 'U':238.029,
			'Np':237,     'Pu':244}
		self.data = {
			'Energy':0,
			'Rg':0,
			'Mass':0,
			'Size':0,
			'FASTA':None,
			'SS':None,
			'Amino Acids':{},
			'Atoms':{},
			'Bonds':{},
			'Coordinates':np.array([[0, 0, 0]])}
	def isfused(self, SC):
		''' Check if an amino acid's sidechain is fused to the backbone '''
		return self.AminoAcids[SC.upper()]['Fused']
	def PDB_entry(self, atom, n, a, l, r, c, s, i, x, y, z, o, t, q, e):
		''' Construct a PDB atom data row '''
		ATOM = '{:<6}'.format(atom)
		N = '{:>5} '.format(n)
		A = '{:<4}'.format(a)
		L = '{:<1}'.format(l)
		R = '{:>3}'.format(r)
		C = '{:>2}'.format(c)
		S = '{:>4}'.format(s)
		I = '{:>1}   '.format(i)
		X = '{:>8.3f}'.format(x)
		Y = '{:>8.3f}'.format(y)
		Z = '{:>8.3f} '.format(z)
		O = '{:>5.2f} '.format(o)
		T = ('{:>5.2f} '.format(t))[:6]
		Q = '{:>10}'.format('')
		E = '{:<2} \n'.format(e)
		entry = ATOM + N + A + L + R + C + S + I + X + Y + Z + O + T + Q + E
		return entry
	def CIF_entry(self, atom, n, a, l, r, c, label_seq, x, y, z, o, t, q, e):
		''' Construct a mmCIF _atom_site data row '''
		alt = '.' if l == '' else l
		charge = '?' if q == 0.0 else '{:.3f}'.format(q)
		fields = [
			atom, str(n), e, a, alt, r, c, '1',
			str(label_seq), '?',
			'{:.3f}'.format(x), '{:.3f}'.format(y),
			'{:.3f}'.format(z),
			'{:.2f}'.format(o), '{:.2f}'.format(t),
			charge,
			str(label_seq), r, c, a, '1']
		return ' '.join(fields) + '\n'
	def atom_residue_iter(self):
		''' Yield (atom_item, coordinate, AAindex) for every atom '''
		AAs    = self.data['Amino Acids']
		AAidx  = 0
		length = len(AAs[AAidx][2]) + len(AAs[AAidx][3]) - 1
		for atom, coord in zip(
				self.data['Atoms'].items(),
				self.data['Coordinates']):
			yield atom, coord, AAidx
			if length:
				length -= 1
			else:
				AAidx += 1
				try:
					length = (len(AAs[AAidx][2]) + len(AAs[AAidx][3]) - 1)
				except (KeyError, IndexError):
					pass
	def Export(self, filename):
		''' Export pose to a .pdb or .cif file '''
		if filename[-3:].upper() == 'PDB':
			with open(filename, 'w') as f:
				DATE = datetime.date.today().strftime("%d-%b-%Y")
				f.write('HEADER'+' '*44+DATE+' '*3+'XXXX'+' '*11+'\n')
				f.write('EXPDTA'+' '*4+'THEORETICAL MODEL'+' '*52+'\n')
				f.write('REMARK 220 REMARK: MODEL GENERATED BY '
				        'SARI SABBAN'+' '*30+'\n')
				AAs = self.data['Amino Acids']
				for atom, coord, AAidx in self.atom_residue_iter():
					line = self.PDB_entry(
						'ATOM', atom[0]+1, atom[1][0], '',
						AAs[AAidx][5], AAs[AAidx][1],
						AAidx+1, '',
						coord[0], coord[1], coord[2],
						atom[1][3], atom[1][4], atom[1][2], atom[1][1])
					f.write(line)
				f.write('TER')
		elif filename[-3:].upper() == 'CIF':
			with open(filename, 'w') as f:
				f.write('data_POSE\n#\n')
				f.write('loop_\n')
				cols = [
					'_atom_site.group_PDB',
					'_atom_site.id',
					'_atom_site.type_symbol',
					'_atom_site.label_atom_id',
					'_atom_site.label_alt_id',
					'_atom_site.label_comp_id',
					'_atom_site.label_asym_id',
					'_atom_site.label_entity_id',
					'_atom_site.label_seq_id',
					'_atom_site.pdbx_PDB_ins_code',
					'_atom_site.Cartn_x',
					'_atom_site.Cartn_y',
					'_atom_site.Cartn_z',
					'_atom_site.occupancy',
					'_atom_site.B_iso_or_equiv',
					'_atom_site.pdbx_formal_charge',
					'_atom_site.auth_seq_id',
					'_atom_site.auth_comp_id',
					'_atom_site.auth_asym_id',
					'_atom_site.auth_atom_id',
					'_atom_site.pdbx_PDB_model_num']
				for col in cols: f.write(col + '\n')
				AAs = self.data['Amino Acids']
				for atom, coord, AAidx in self.atom_residue_iter():
					line = self.CIF_entry(
						'ATOM', atom[0]+1, atom[1][0], '',
						AAs[AAidx][5], AAs[AAidx][1],
						AAidx+1,
						coord[0], coord[1], coord[2],
						atom[1][3], atom[1][4], atom[1][2], atom[1][1])
					f.write(line)
				f.write('#\n')
	def GetAtom(self, AA, atom):
		''' Get specific atom coordinates '''
		info = self.data['Amino Acids'][AA]
		indexes = info[2] if atom in self.BB_ATOMS else info[3]
		for i in indexes:
			if self.data['Atoms'][i][0] == atom:
				return self.data['Coordinates'][i]
		raise Exception(f'Amino acid does not have the {atom} atom')
	def Insert(self, AA, X, Y, Z):
		''' Inser a backbone or sidechain given its initial coordinates '''
		if len(AA) == 1: AA = AA.upper()
		atoms = np.array(self.AminoAcids[AA]['Vectors']) + np.array([X, Y, Z])
		return atoms
	def Flip(self, AA):
		''' Flip an amino acid 180 degrees on CA's H1 H2 axis'''
		p = AA[2]
		AA = AA - p
		H1 = AA[3]
		H2 = AA[4]
		u = np.cross(H1, H2)
		lu = np.linalg.norm(u)
		u = u / lu
		TM = np.array([
		[2*u[0]**2-1, 2*u[0]*u[1], 2*u[0]*u[2]],
		[2*u[0]*u[1], 2*u[1]**2-1, 2*u[2]*u[2]],
		[2*u[0]*u[2], 2*u[2]*u[2], 2*u[2]**2-1]])
		AA = np.matmul(AA, TM)
		AA = AA + p
		return AA
	def LD(self, AA):
		''' Convert an amino acid between L and D chirality '''
		AA = AA * [1, 1, -1]
		return AA
	def Amino(self, backbone_type, X, Y, Z, aa, index, flip=False, LD=False):
		''' Construct an amino acid and add its coordinates to the data '''
		BB = self.Insert(backbone_type, X, Y, Z)
		SC = self.Insert(aa, X, Y, Z)
		AA = np.insert(BB, index, SC, axis=0)
		if LD: AA = self.LD(AA)
		if flip: AA = self.Flip(AA)
		if self.isfused(aa): AA = np.delete(AA, [1], axis=0)
		self.data['Coordinates'] = \
		np.append(self.data['Coordinates'], AA, axis=0)
		if backbone_type == 'Backbone' or backbone_type == 'Backbone start':
			self.data['Coordinates'] = \
			np.delete(self.data['Coordinates'], [0], axis=0)
	def Atoms(self, AA, chain, backbone_type, BB_index, AA_index, I, LD=False):
		''' Construct, and add to pose, atom and amino acid identities '''
		BB = backbone_type[:BB_index]
		if self.isfused(AA): BB.pop(1)
		BB = BB + self.AminoAcids[AA.upper()]['Sidechain Atoms']
		BB = BB + backbone_type[BB_index:]
		BBi, SCi = [], []
		for atomi, v in enumerate(BB, I):
			self.data['Atoms'][atomi] = [v[0], v[1], v[2], v[3], v[4]]
			(BBi if v[0] in self.BB_ATOMS else SCi).append(atomi)
		tri = self.AminoAcids[AA.upper()]['Tricode']
		if LD: tri = 'D' + tri[1:]
		self.data['Amino Acids'][AA_index] = [AA, chain, BBi, SCi, 'L', tri, 0]
	def BondTree_fused(self, BB, SC):
		''' Construct bond graph for when a sidechain is fused to a backbone '''
		BBb = {int(k): v for k, v in
			copy.deepcopy(self.AminoAcids[BB]['Bonds']).items()}
		SCb = {int(k): v for k, v in
			copy.deepcopy(self.AminoAcids[SC]['Bonds']).items()}
		length = len(SCb)
		BBb.pop(1)
		nBBb = {}
		for i, a in enumerate(BBb.items()):
			v = a[1]
			v = [x if x==0 else x-1 for x in v]
			nBBb[i] = v
		if BB == 'Backbone' or BB == 'Backbone start':
			n = 3
			nBBb[0][0] = length+1
			BBb = nBBb
		else:
			n = 1
			nBBb[0][0] = length-1
			BBb = nBBb
		for i in reversed(range(len(BBb))):
			if i > n+1:
				oldvals = BBb[i]
				newvals = [x if x<=n else x+length-1 for x in BBb[i]]
				oldk = i
				newk = i+length-1
				del BBb[i]
				BBb[newk] = newvals
		BBb[n].append(n+1+length)
		for i, (k, v) in enumerate(SCb.items(), start=n+2):
			if k < 0: break
			k = i
			if BB == 'Backbone' or BB == 'Backbone start':
				v = [x+n+2 for x in v]
			else:
				v = [x+n+4 if x<0 else x+n+2 for x in v]
			if i == n+2: v.append(n)
			BBb[k] = sorted(v)
		return BBb
	def BondTree_AA(self, BB, SC):
		''' Construct amino acid bond graph by adding sidechain to backbone '''
		SC = SC.upper()
		if self.isfused(SC):
			BBb = self.BondTree_fused(BB, SC)
			return BBb
		BBb = {int(k): v for k, v in
			copy.deepcopy(self.AminoAcids[BB]['Bonds']).items()}
		SCb = {int(k): v for k, v in
			copy.deepcopy(self.AminoAcids[SC]['Bonds']).items()}
		length = len(SCb)
		if BB == 'Backbone' or BB == 'Backbone start':
			n = 4
		else:
			n = 2
		for i in reversed(range(len(BBb))):
			if i > n+1:
				oldvals = BBb[i]
				newvals = [x if x<=n else x+length for x in BBb[i]]
				oldk = i
				newk = i+length
				del BBb[i]
				BBb[newk] = newvals
		BBb[n].append(n + 2 + length)
		for i, (k, v) in enumerate(SCb.items(), start=n+2):
			k = i
			if length != 1:
				v = [x+n+2 for x in v]
				if i == n+2: v.append(n)
			else:
				v = [x+n+1 for x in v]
			BBb[k] = sorted(v)
		return BBb
	def BondTree(self, BB, AA):
		''' Update the pose bond graph when adding a new amino acid '''
		BBb = self.BondTree_AA(BB, AA)
		BT = self.data['Bonds']
		length = len(BT)
		if length == 0:
			self.data['Bonds'] = BBb
			return
		i_max = max(BT)
		BT[i_max-1] += [i_max+1]
		for i in range(len(BBb)):
			K = i+length
			v = BBb[i]
			V = [x+length for x in v]
			if i == 0: V.append(i_max-1)
			BT[K] = V
		self.data['Bonds'] = BT
	def update_data(self):
		''' Update cached properties after structural changes '''
		self.data['Mass']  = self.Mass()
		self.data['FASTA'] = ''.join(self.FASTA())
		self.data['SS']    = ''.join(self.SecondaryStructures())
		self.data['Size']  = self.Size()
		self.data['Rg']    = self.Rg()
	def FASTA(self):
		''' Return FASTA sequence of peptide as a string '''
		return [x[0] for x in self.data['Amino Acids'].values()]
	def SecondaryStructures(self):
		''' Return secondary strucutre of each amino acid of the peptide '''
		return [x[4] for x in self.data['Amino Acids'].values()]
	def Distance(self, AA1, atom1, AA2, atom2):
		''' Measure distance between any two atoms '''
		A = self.GetAtom(AA1, atom1)
		B = self.GetAtom(AA2, atom2)
		mag = np.linalg.norm(B - A)
		return mag
	def Size(self):
		''' Calculate length of peptide '''
		return len(self.data['Amino Acids'])
	def AtomList(self, PDB=False):
		''' Return list of all the atoms '''
		idx = 0 if PDB else 1
		return [x[idx] for x in self.data['Atoms'].values()]
	def Identify(self, index, item, q=False):
		''' Identify an atom, atom charge, or amino acid given its index '''
		if item.upper() == 'ATOM':
			Atom = self.data['Atoms'][index]
			if q: return Atom[-1]
			else: return Atom[0]
		elif item.upper() == 'RESIDUE' or item.upper() == 'AMINO ACID':
			AminoAcid = self.data['Amino Acids'][index][0]
			return AminoAcid
		else:
			raise Exception('Incorrect item')
	def Mass(self):
		''' Calculate mass of peptide in Da'''
		mass = sum(self.Masses[x] for x in self.AtomList())
		return round(mass, 3)
	def Rg(self):
		''' Calculate the radius of gyration of a peptide '''
		mass  = np.array([self.Masses[e] for e in self.AtomList()])
		tmass = mass.sum()
		if tmass == 0: raise ZeroDivisionError('No atoms in pose')
		coord = self.data['Coordinates']
		xm    = coord * mass[:, np.newaxis]
		rr    = np.sum(coord * xm)
		mm    = np.sum((xm.sum(0) / tmass) ** 2)
		return round(math.sqrt(rr / tmass - mm), 3)
	def Atom3Angle(self, AA1, atom1, AA2, atom2, AA3, atom3):
		''' Measure the angle between three atoms '''
		atom1 = self.GetAtom(AA1, atom1)
		atom2 = self.GetAtom(AA2, atom2)
		atom3 = self.GetAtom(AA3, atom3)
		A = atom2 - atom1
		B = atom2 - atom3
		cos_theta = np.dot(A, B) / (np.linalg.norm(A) * np.linalg.norm(B))
		return math.degrees(math.acos(cos_theta))
	def GetBondAtoms(self, index1, index2):
		''' Get the atom pair that participate in a bond from their index '''
		bonds = self.data['Bonds'][index1]
		if index2 not in bonds:
			error = 'Requested two atoms are not bonded'
			raise Exception(error)
		atomA = self.data['Atoms'][index1][0]
		elementA = self.data['Atoms'][index1][1]
		atomB = self.data['Atoms'][index2][0]
		elementB = self.data['Atoms'][index2][1]
		return [atomA, elementA, atomB, elementB]
	def Info(self):
		''' Print all basic info about a peptide '''
		print('Sequence:\t{}'.format(self.data['FASTA']))
		print('SS:\t\t{}'.format(''.join(self.SecondaryStructures())))
		print('Mass:\t\t{} Da'.format(self.data['Mass']))
		print('Size:\t\t{} residues'.format(self.data['Size']))
		print('Rg:\t\t{} Å'.format(self.data['Rg']))
		print('Energy:\t\t{}'.format(self.data['Energy']))
	def Build(self, sequence, chain='A'):
		''' Build a polypeptide primary structure from sequence '''
		X, Y, Z = 0, 0, 0
		Eadj = (0.400, 1.472, 0)
		Oadj = (0.812, 0.940, 0)
		n    = len(sequence)
		for i, aa in enumerate(sequence):
			LD, last, odd = aa.islower(), i == n-1, (i%2) != 0
			if n == 1 or i == 0:
				bb  = 'Backbone' if n == 1 else 'Backbone start'
				idx = [6]
				I   = len(self.data['Coordinates']) - 1
				flip = False
			else:
				bb   = 'Backbone end' if last else 'Backbone middle'
				adj  = Eadj if odd else Oadj
				prev = self.data['Coordinates'][-2]
				X    = prev[0] + adj[0]
				Y    = prev[1] + adj[1]
				Z    = prev[2] + adj[2]
				idx  = [4]
				I    = len(self.data['Coordinates'])
				flip = odd
			self.Amino(bb, X, Y, Z, aa, idx, flip=flip, LD=LD)
			AAs = self.AminoAcids[bb]['Backbone Atoms']
			self.Atoms(aa, chain, AAs, idx[0], i, I, LD=LD)
			self.BondTree(bb, aa)
		self.update_data()
	def Adjust(self, AA1, atom1, AA2, atom2, length):
		''' Change the distance between any two atoms '''
		if (atom1 not in {'N', 'CA', 'C', 'O'}
		or  atom2 not in {'N', 'CA', 'C', 'O'}):
			index = (self.data['Amino Acids'][AA1][2]
			         + self.data['Amino Acids'][AA1][3])
			atoms_in = self.data['Atoms']
			Ai = next(i for i in index if atoms_in[i][0] == atom1)
			Bi = next(i for i in index if atoms_in[i][0] == atom2)
			coordinates = self.data['Coordinates']
			vectors = {}
			for k, v in self.data['Bonds'].items():
				vectors[k] = [coordinates[x] - coordinates[k] for x in v]
			Bidx = next(
				i for i, b in enumerate(self.data['Bonds'][Ai])
				if b == Bi)
			v = vectors[Ai][Bidx]
			mag = np.linalg.norm(v)
			v = v*(length/mag)
			vectors[Ai][Bidx] = v
			temp = {}
			Bond_Coord = {0: self.data['Coordinates'][0]}
			for i in range(len(vectors)):
				temp[i] = vs = [Bond_Coord[i] + x for x in vectors[i]]
				for b, v in zip(self.data['Bonds'][i], vs):
					Bond_Coord[b] = v
			coordinates = [0] * len(temp)
			for k, vs in temp.items():
				for b, v in zip(self.data['Bonds'][k], vs):
					coordinates[b] = v
			coordinates = np.array(coordinates)
			self.data['Coordinates'] = coordinates
		else:
			A = self.GetAtom(AA1, atom1)
			B = self.GetAtom(AA2, atom2)
			mag = math.sqrt(np.sum((B-A)**2))
			mut = length/mag
			sc1 = {x[0] for x in self.AminoAcids[
				self.data['Amino Acids'][AA1][0].upper()
				]['Sidechain Atoms']}
			sc2 = {x[0] for x in self.AminoAcids[
				self.data['Amino Acids'][AA2][0].upper()
				]['Sidechain Atoms']}
			if atom1 in sc1 or atom2 in sc2:
				raise Exception(
					'Distance adjustments allowed only for backbone')
			crds = self.data['Coordinates']
			Aindex = np.argwhere((crds == A).all(axis=1))[0][0]
			Bindex = np.argwhere((crds == B).all(axis=1))[0][0]
			before = crds[:Bindex]
			after  = crds[Bindex:]
			nB = (B-A) * mut
			after = after - (B-A) + nB
			self.data['Coordinates'] = np.concatenate((before, after))
	def Angle(self, AA, angle_type, chi_type=None):
		''' Measure angle at bond '''
		AminoAcid = self.data['Amino Acids'][AA][0].upper()
		at = angle_type.upper()
		if at == 'PHI':
			if AA == 0: return 0.0
			r1 = self.GetAtom(AA-1, 'C')
			r2 = self.GetAtom(AA, 'N')
			r3 = self.GetAtom(AA, 'CA')
			r4 = self.GetAtom(AA, 'C')
		elif at == 'PSI':
			r1 = self.GetAtom(AA, 'N')
			r2 = self.GetAtom(AA, 'CA')
			r3 = self.GetAtom(AA, 'C')
			try:
				r4 = self.GetAtom(AA+1, 'N')
			except:
				return 0.0
		elif at == 'OMEGA':
			r1 = self.GetAtom(AA, 'CA')
			r2 = self.GetAtom(AA, 'C')
			try:
				r3 = self.GetAtom(AA+1, 'N')
				r4 = self.GetAtom(AA+1, 'CA')
			except: return 180.0
		elif at == 'CHI':
			assert type(chi_type) is int, 'Incorrect Chi angle type'
			n_chi = len(self.AminoAcids[AminoAcid]['Chi Angle Atoms'])
			if n_chi < chi_type:
				raise Exception(
					f'{AminoAcid} at position {AA} '
					f'has no Chi {chi_type} angle')
			atoms = self.AminoAcids[AminoAcid]['Chi Angle Atoms'][chi_type-1]
			r1 = self.GetAtom(AA, atoms[0])
			r2 = self.GetAtom(AA, atoms[1])
			r3 = self.GetAtom(AA, atoms[2])
			r4 = self.GetAtom(AA, atoms[3])
		u1 = r2 - r1
		u2 = r3 - r2
		u3 = r4 - r3
		mag_u2 = np.linalg.norm(u2)
		u1u2 = np.cross(u1, u2)
		u2u3 = np.cross(u2, u3)
		u1u2Cu2u3 = np.cross(u1u2, u2u3)
		u1u2Du2u3 = np.dot(u1u2, u2u3)
		a = np.dot(u2, u1u2Cu2u3)
		b = mag_u2 * u1u2Du2u3
		theta = math.atan2(a, b) * 180 / math.pi
		return theta
	def rotate_backbone(self, split, ori, A, B, current, theta):
		''' Apply zero-then-rotate to coordinates from split onward '''
		before = self.data['Coordinates'][:split]
		after  = self.data['Coordinates'][split:] - ori
		u = B - A
		u = u / np.linalg.norm(u)
		after = np.matmul(after, self.Rotation_Matrix(-current, u))
		after = np.matmul(after, self.Rotation_Matrix(theta, u))
		self.data['Coordinates'] = np.append(before, after + ori, axis=0)
	def Rotation_Matrix(self, theta, u):
		''' Rotate a matrix around axis u by theta angle '''
		ux, uy, uz = u[0], u[1], u[2]
		S = math.sin(math.radians(theta))
		C = math.cos(math.radians(theta))
		R = np.array([
		[C+ux**2*(1-C)   , ux*uy*(1-C)-uz*S, ux*uz*(1-C)+uy*S],
		[uy*ux*(1-C)+uz*S, C+uy**2*(1-C)   , uy*uz*(1-C)-ux*S],
		[uz*ux*(1-C)-uy*S, uz*uy*(1-C)+ux*S, C+uz**2*(1-C)   ]])
		return R
	def Rotate(self, AA, theta, angle_type, chi_type=None):
		''' Rotate around a bond '''
		AminoAcid = self.data['Amino Acids'][AA][0].upper()
		at = angle_type.upper()
		if at == 'PHI':
			n = 3 if AA == 0 else 1
			split = self.data['Amino Acids'][AA][2][2] + n
			ori   = self.GetAtom(AA, 'CA')
			self.rotate_backbone(split, ori,
				self.GetAtom(AA, 'CA'), self.GetAtom(AA, 'N'),
				self.Angle(AA, 'phi'), theta)
		elif at == 'PSI':
			n = 3 if AA == 0 else 1
			split = self.data['Amino Acids'][AA][2][4] + n
			ori   = self.GetAtom(AA, 'C')
			self.rotate_backbone(split, ori,
				self.GetAtom(AA, 'C'), self.GetAtom(AA, 'CA'),
				self.Angle(AA, 'psi'), theta)
		elif at == 'OMEGA':
			split = self.data['Amino Acids'][AA + 1][2][0]
			ori   = self.GetAtom(AA + 1, 'N')
			self.rotate_backbone(split, ori,
				self.GetAtom(AA + 1, 'N'), self.GetAtom(AA, 'C'),
				self.Angle(AA, 'omega'), theta)
		elif at == 'CHI':
			assert type(chi_type) is int, 'Incorrect Chi angle type'
			n_chi = len(self.AminoAcids[AminoAcid]['Chi Angle Atoms'])
			if n_chi < chi_type:
				raise Exception(
					f'{AminoAcid} at position {AA} '
					f'has no Chi {chi_type} angle')
			atoms = self.AminoAcids[AminoAcid]['Chi Angle Atoms'][chi_type-1]
			A = self.GetAtom(AA, atoms[1])
			B = self.GetAtom(AA, atoms[2])
			ori = B
			start = self.AminoAcids[AminoAcid]['Chi Angle Atoms'][chi_type-1][2]
			L = self.AminoAcids[AminoAcid]['Sidechain Atoms']
			i = [x[0] for x in L].index(start)
			Sindex = self.data['Amino Acids'][AA][3][i]
			Eindex = self.data['Amino Acids'][AA][3][-1]
			before = self.data['Coordinates'][:Sindex]
			side   = self.data['Coordinates'][Sindex:Eindex + 1]
			after  = self.data['Coordinates'][Eindex + 1 :]
			side = side - ori
			u = A - B
			lu = np.linalg.norm(u)
			u = u / lu
			current = self.Angle(AA, 'chi', chi_type)
			zeroing = 0 - current
			RM = self.Rotation_Matrix(zeroing, u)
			side = np.matmul(side, RM)
			RM = self.Rotation_Matrix(theta, u)
			side = np.matmul(side, RM)
			side = side + ori
			combine = np.append(before, side, axis=0)
			combine = np.append(combine, after, axis=0)
			self.data['Coordinates'] = combine
	def Rotation3Angle(self, AA1, atom1, AA2, atom2, AA3, atom3, theta):
		''' Change angle between three atoms '''
		atoms = self.data['Atoms']
		BB = self.data['Amino Acids'][AA2][2]
		atom2i = None
		for i in BB:
			if atoms[i][0] == atom2: atom2i = i
		if atom2i == None:
			raise Exception('Chosen atom not in backbone')
		before = self.data['Coordinates'][:atom2i]
		after  = self.data['Coordinates'][atom2i:]
		A = self.GetAtom(AA3, atom3) - self.GetAtom(AA1, atom1)
		B = self.GetAtom(AA3, atom3) - self.GetAtom(AA2, atom2)
		u = np.cross(B, A)
		lu = np.linalg.norm(u)
		u = u / lu
		ori = self.GetAtom(AA2, atom2)
		after = after - ori
		RM = self.Rotation_Matrix(theta, u)
		after = np.matmul(after, RM)
		after = after + ori
		combine = np.append(before, after, axis=0)
		self.data['Coordinates'] = combine
	def RigidMotion(self, AA, A, B, BB='Backbone middle'):
		''' Superimpose amino B into A '''
		n, e = 0, 0
		if BB == 'Backbone start': n = 2
		if BB == 'Backbone end': e = 1
		A = np.c_[A, np.ones(len(A))]
		B = np.c_[B, np.ones(len(B))]
		if AA == 'G':
			Aa, Ao, Ab, Ac = A[0], A[1], A[3], A[2]
			Ba, Bo, Bb, Bc = B[0], B[2+n], B[-1], B[-2-e]
			AL = np.array([Aa - Ao, Ab - Ao, Ac - Ao, Ao])
			BL = np.array([Ba - Bo, Bb - Bo, Bc - Bo, Bo])
			BL[1][2] = 1
			BL_= np.linalg.inv(BL)
		elif self.isfused(AA):
			Aa, Ao, Ab, Ac = A[0], A[1], A[4], A[2]
			Ba, Bo, Bb, Bc = B[0], B[1+n], B[3], B[-2-e]
			AL = np.array([Aa - Ao, Ab - Ao, Ac - Ao, Ao])
			BL = np.array([Ba - Bo, Bb - Bo, Bc - Bo, Bo])
			BL[1][2] = 1
			BL_= np.linalg.inv(BL)
		else:
			Aa, Ao, Ab, Ac = A[0], A[1], A[4], A[2]
			Ba, Bo, Bb, Bc = B[0], B[2+n], B[4+n], B[-2-e]
			AL = np.array([Aa - Ao, Ab - Ao, Ac - Ao, Ao])
			BL = np.array([Ba - Bo, Bb - Bo, Bc - Bo, Bo])
			BL_= np.linalg.inv(BL)
		M = np.matmul(BL_, AL)
		B = [np.matmul(i, M)[:3] for i in B]
		B = np.array(B)
		Aoxy = A[3][:3]
		B[-1] = Aoxy
		return B
	def Mutate(self, index, AA):
		''' Mutate an amino acid to a different amino acid '''
		seq = ''.join(self.FASTA())
		self.ReBuild(seq[:index] + AA + seq[index+1:])
	def Import(self, filename, chain='A', model=1):
		''' Import a structure from a .pdb or .cif file '''
		if filename[-3:].upper() == 'PDB':
			ATOM, N, A, L, R, C, S, I, X, Y, Z, O, T, Q, E = \
			[], [], [], [], [], [], [], [], [], [], [], [], [], [], []
			has_models   = False
			in_target    = False
			found_models = []
			with open(filename) as f:
				for line in f:
					line = line.strip()
					if not line:
						continue
					record = line.split()[0]
					if record == 'MODEL':
						has_models = True
						try:
							mnum = int(line.split()[1])
						except (IndexError, ValueError):
							mnum = len(found_models) + 1
						found_models.append(mnum)
						in_target = (mnum == model)
					elif record == 'ENDMDL':
						if in_target:
							break
						in_target = False
					elif record == 'ATOM' \
					and line.split()[4] == chain \
					and (not has_models or in_target):
						ATOM.append(line[:4].strip())
						N.append(int(line[6:11].strip()))
						A.append(line[12:16].strip())
						L.append(line[16].strip())
						R.append(line[17:20].strip())
						C.append(line[21].strip())
						S.append(int(line[22:26].strip()))
						I.append(line[26].strip())
						X.append(float(line[30:38].strip()))
						Y.append(float(line[38:46].strip()))
						Z.append(float(line[46:54].strip()))
						O.append(float(line[54:60].strip()))
						T.append(float(line[60:66].strip()))
						q = line[70:76].strip()
						Q.append(float(q) if q else 0.0)
						E.append(line[76:78].strip())
			if has_models and model not in found_models:
				raise Exception(
					f'Model {model} not found in '
					f'{filename}. '
					f'Available models: {found_models}')
		elif filename[-3:].upper() == 'CIF':
			ATOM, N, A, L, R, C, S, I, X, Y, Z, O, T, Q, E = \
			[], [], [], [], [], [], [], [], [], [], [], [], [], [], []
			with open(filename) as f:
				lines = f.readlines()
			col = {}
			col_index = 0
			data_start = 0
			for idx, line in enumerate(lines):
				if line.strip() == 'loop_':
					nxt = lines[idx+1].strip() if idx+1 < len(lines) else ''
					if nxt.startswith('_atom_site.'):
						i = idx + 1
						while i < len(lines) and \
						lines[i].strip().startswith('_atom_site.'):
							colname = \
							lines[i].strip().split('.')[1]
							col[colname] = col_index
							col_index += 1
							i += 1
						data_start = i
						break
			i_group  = col['group_PDB']
			i_type   = col['type_symbol']
			i_altloc = col['label_alt_id']
			i_charge = col['pdbx_formal_charge']
			i_x      = col['Cartn_x']
			i_y      = col['Cartn_y']
			i_z      = col['Cartn_z']
			i_occ    = col['occupancy']
			i_bfac   = col['B_iso_or_equiv']
			i_chain  = col['auth_asym_id']
			i_atom   = col['auth_atom_id']
			i_resn   = col['auth_comp_id']
			i_seqid  = col['auth_seq_id']
			i_serial     = col['id']
			i_model_num  = col.get('pdbx_PDB_model_num', None)
			found_models = []
			for line in lines[data_start:]:
				ln = line.strip()
				if not ln or ln == '#':
					break
				fields = ln.split()
				if fields[i_group] != 'ATOM':
					continue
				if fields[i_chain] != chain:
					continue
				if i_model_num is not None:
					mnum = int(fields[i_model_num])
					if mnum not in found_models:
						found_models.append(mnum)
					if mnum != model:
						continue
				ATOM.append(fields[i_group])
				N.append(int(fields[i_serial]))
				A.append(fields[i_atom])
				L.append('' if (alt:=fields[i_altloc]) == '.' else alt)
				R.append(fields[i_resn])
				C.append(fields[i_chain])
				S.append(int(fields[i_seqid]))
				I.append('')
				X.append(float(fields[i_x]))
				Y.append(float(fields[i_y]))
				Z.append(float(fields[i_z]))
				O.append(float(fields[i_occ]))
				T.append(float(fields[i_bfac]))
				raw_q = fields[i_charge]
				Q.append(0.0 if raw_q == '?' \
				else float(raw_q))
				E.append(fields[i_type])
			if i_model_num is not None \
			and found_models \
			and model not in found_models:
				raise Exception(
					f'Model {model} not found in '
					f'{filename}. '
					f'Available models: {found_models}')
		if not N: raise Exception(f'No ATOM in chain {chain} for {filename}')
		N = [x-N[0] for x in N]
		S_first, S = S[0], [x-S[0] for x in S]
		best = {}
		for i in range(len(A)):
			key = (S[i], A[i])
			if key not in best:
				best[key] = i
			elif O[i] > O[best[key]]:
				best[key] = i
		keep = sorted(best.values())
		A, R, C, S, X, Y, Z, O, T, Q, E = [[l[i] for i in keep]
			for l in [A, R, C, S, X, Y, Z, O, T, Q, E]]
		ALL = [list(row) for row in zip(A, R, C, S, X, Y, Z, O, T, Q, E)]
		Structure = defaultdict(list)
		for atom in ALL: Structure[atom[3]].append(atom)
		for k, v in Structure.items():
			seen = set()
			Structure[k] = [e for e in v
				if e[0] not in seen and not seen.add(e[0])]
		count = 0
		Atoms = {}
		Aminos = {}
		Coordinates = []
		for k, v in Structure.items():
			BB, SC = [], []
			for atom, amino, chain, residue, x, y, z, o, t, c, e in v:
				Coordinates.append([x, y, z])
				Atoms[count] = [atom, e, c, o, t]
				(BB if atom in self.BB_ATOMS else SC).append(count)
				count += 1
			tricode = amino
			amino = next(
				k for k, v in self.AminoAcids.items()
				if v['Tricode'] == amino)
			Aminos[k] = [amino, chain, BB, SC, 'L', tricode, 0]
		Coordinates = np.array(Coordinates)
		errors = []
		required_bb = {'N', 'CA', 'C'}
		sorted_keys = sorted(Aminos.keys())
		for k in sorted_keys:
			present = {Atoms[ai][0] for ai in Aminos[k][2]}
			missing = required_bb - present
			if missing:
				orig = k + S_first
				tri  = Aminos[k][5]
				errors.append(
					f'  residue {orig} ({tri}): '
					f'missing atom(s) {sorted(missing)}')
		for ki, kj in zip(sorted_keys[:-1], sorted_keys[1:]):
			C_idx = next(
				(ai for ai in Aminos[ki][2]
				if Atoms[ai][0] == 'C'), None)
			N_idx = next(
				(ai for ai in Aminos[kj][2]
				if Atoms[ai][0] == 'N'), None)
			if C_idx is None or N_idx is None:
				continue
			dist = np.linalg.norm(
				Coordinates[C_idx] - Coordinates[N_idx])
			if dist > 2.0:
				orig_i  = ki + S_first
				orig_j  = kj + S_first
				gap     = kj - ki - 1
				tri_i   = Aminos[ki][5]
				tri_j   = Aminos[kj][5]
				gap_str = (
					f', {gap} residue(s) missing'
					if gap > 0 else '')
				errors.append(
					f'  residue {orig_i} ({tri_i}) \u2192 '
					f'{orig_j} ({tri_j}): '
					f'C-N = {dist:.2f} \u00c5{gap_str}')
		if errors:
			raise Exception(
				f'Broken chain in {filename} '
				f'chain {chain}:\n'
				+ '\n'.join(errors))
		Aminos = {i: v for i, v in enumerate(Aminos.values())}
		self.data['Coordinates'] = Coordinates
		self.data['Amino Acids'] = Aminos
		self.data['Atoms'] = Atoms
		sequence = ''.join(self.FASTA())
		for i, aa in enumerate(sequence):
			bb = ('Backbone start' if i == 0 else
			      'Backbone end'   if i == len(sequence)-1 else
			      'Backbone middle')
			self.BondTree(bb, aa)
		self.update_data()
	def ReBuild(self, sequence=None, D_AA=False):
		''' Fold a polypeptide using angles and bonds '''
		if sequence == None:
			sequence = self.data['FASTA']
		PHIs, PSIs, OMGs = [], [], []
		NCaC, CaCN, CNCa, CHIs = [], [], [0], {}
		bNCA, bCAC, bCN1 = [], [], []
		for i in range(len(sequence)):
			PHIs.append(self.Angle(i, 'PHI'))
			PSIs.append(self.Angle(i, 'PSI'))
			OMGs.append(self.Angle(i, 'OMEGA'))
			NCaC.append(self.Atom3Angle(i, 'N', i, 'CA', i, 'C'))
			if i != 0:
				CNCa.append(self.Atom3Angle(i-1, 'C', i, 'N', i, 'CA'))
			if i != len(sequence) -1:
				CaCN.append(self.Atom3Angle(i, 'CA', i, 'C', i+1, 'N'))
			chi = []
			for number in range(1, 21):
				try: chi.append(self.Angle(i, 'CHI', number))
				except: pass
			CHIs[i] = chi
			bNCA.append(self.Distance(i, 'N', i, 'CA'))
			bCAC.append(self.Distance(i, 'CA', i, 'C'))
			try: bCN1.append(self.Distance(i, 'C', i+1, 'N'))
			except: pass
		self.data = copy.deepcopy({
			'Energy':0, 'Rg':0, 'Mass':0, 'Size':0,
			'FASTA':None, 'SS':None,
			'Amino Acids':{}, 'Atoms':{}, 'Bonds':{},
			'Coordinates':np.array([[0, 0, 0]])})
		self.Build(sequence)
		for i, (p, s, o, n, a, c, b1, b2, b3) in enumerate(zip(
		PHIs, PSIs, OMGs, NCaC, CaCN, CNCa, bNCA, bCAC, bCN1)):
			self.Rotate(i, p, 'PHI')
			self.Rotate(i, s, 'PSI')
			self.Adjust(i, 'N', i, 'CA', b1)
			self.Adjust(i, 'CA', i, 'C', b2)
			N = self.Atom3Angle(i, 'N', i, 'CA', i, 'C')
			self.Rotation3Angle(i, 'N', i, 'CA', i, 'C', N-n)
			if i != 0:
				C = self.Atom3Angle(i-1, 'C', i, 'N', i, 'CA')
				self.Rotation3Angle(i-1, 'C', i, 'N', i, 'CA', C-c)
			if i != len(sequence) -1:
				A = self.Atom3Angle(i, 'CA', i, 'C', i+1, 'N')
				self.Rotation3Angle(i, 'CA', i, 'C', i+1, 'N', A-a)
				self.Rotate(i, o, 'OMEGA')
				self.Adjust(i, 'C', i+1, 'N', b3)
		for i in range(len(sequence)):
			chi = CHIs[i]
			if not chi or self.isfused(sequence[i]): continue
			try:
				for ii, c in enumerate(chi):
					self.Rotate(i, c, 'CHI', ii+1)
			except: continue
		self.Gasteiger()
		self.DSSP()
		self.SASA()
		self.update_data()
		if D_AA:
			self.data['Coordinates'] = self.data['Coordinates'] * [1, 1, -1]
			for i in range(len(sequence)):
				Daa = self.data['Amino Acids'][i][0].lower()
				tri = 'D' + self.data['Amino Acids'][i][5][1:]
				self.data['Amino Acids'][i][0] = Daa
				self.data['Amino Acids'][i][-1] = tri
	def Gasteiger(self, iterations=6):
		''' Calculate Gasteiger-Marsili partial charges to all atoms '''
		PARAMS = {
			'C3': (7.98,  9.18,  1.88),
			'C2': (8.79,  9.32,  1.51),
			'C1': (10.39, 9.45,  0.73),
			'H':  (7.17,  6.24, -0.56),
			'O3': (14.18, 12.92, 1.39),
			'O2': (17.07, 13.79, 0.47),
			'N3': (11.54, 10.82, 1.36),
			'N2': (12.87, 11.15, 0.85),
			'S':  (10.14,  9.13, 1.38),
			'Se': (9.00,   8.00, 1.10)}
		ids  = sorted(self.data['Atoms'].keys())
		crds = self.data['Coordinates']
		els  = [self.data['Atoms'][i][1].upper() for i in ids]
		c = crds[np.array(ids)]
		dm = np.sqrt(((c[:, None, :] - c[None, :, :]) ** 2).sum(2))
		is_H = np.array([e == 'H'         for e in els])
		is_S = np.array([e in ('S', 'SE') for e in els])
		heavy_thresh = np.full((len(ids), len(ids)), 1.9)
		h_mask = is_H[:, None] | is_H[None, :]
		s_mask = is_S[:, None] | is_S[None, :]
		heavy_thresh[h_mask] = 1.3
		heavy_thresh[s_mask] = 2.1
		bond_mask = (dm < heavy_thresh) & (dm > 0.0)
		bonds = {i: [] for i in ids}
		for ii, jj in np.argwhere(bond_mask):
			bonds[ids[ii]].append(ids[jj])
		heavy = ~is_H
		short = (dm < 1.42) & (dm > 0)
		sp2_mask = short & heavy[:, None] & heavy[None, :]
		sp2 = {ids[ii] for ii in np.where(sp2_mask.any(axis=1))[0]}
		def types(ii, i):
			''' Classifies each atom into a Gasteiger atom type '''
			el = els[ii]
			if el == 'H':  return 'H'
			if el == 'S':  return 'S'
			if el == 'SE': return 'Se'
			nb    = len(bonds[i])
			isp2  = i in sp2
			if el == 'C':
				if isp2:    return 'C2'
				if nb <= 2: return 'C1'
				return 'C3'
			if el == 'N':
				return 'N2' if isp2 else 'N3'
			if el == 'O':
				return 'O2' if isp2 else 'O3'
			return 'C3'
		charges = {i: self.data['Atoms'][i][2] for i in ids}
		atype   = {i: PARAMS[types(ii, i)] for ii, i in enumerate(ids)}
		for n in range(iterations):
			damp = 1.0 / (2 ** (n + 1))
			chi = {i: a + q*(b + c*q) for i in ids
				for a, b, c in [atype[i]] for q in [charges[i]]}
			delta = {i: 0.0 for i in ids}
			for i in ids:
				for j in bonds[i]:
					if j <= i:
						continue
					if chi[j] >= chi[i]:
						donor, acceptor = i, j
					else:
						donor, acceptor = j, i
					a, b, c = atype[donor]
					ip = a + b + c
					if ip == 0:
						continue
					dq = damp * (
						chi[acceptor] - chi[donor]) / ip
					delta[donor]    += dq
					delta[acceptor] -= dq
			for i in ids:
				charges[i] += delta[i]
		for i in ids:
			self.data['Atoms'][i][2] = round(charges[i], 4)
	def DSSP(self):
		''' Assign secondary structures using the DSSP algorithm '''
		N = self.data['Size']
		AAs      = self.data['Amino Acids']
		chains   = [AAs[i][1]         for i in range(N)]
		tricodes = [AAs[i][5].upper() for i in range(N)]
		H_pos = [None] * N
		for i in range(N):
			if 'PRO' in tricodes[i]:
				continue
			if i == 0 or chains[i] != chains[i - 1]:
				continue
			for hname in ('1H', 'H'):
				try:
					H_pos[i] = self.GetAtom(i, hname)
					break
				except Exception:
					pass
			else:
				try:
					Ni = self.GetAtom(i, 'N')
					Cp = self.GetAtom(i - 1, 'C')
					d  = Ni - Cp
					nm = np.linalg.norm(d)
					if nm > 0.001:
						H_pos[i] = Ni + (d / nm) * 1.01
				except Exception:
					pass
		hbond = set()
		for i in range(N):
			if H_pos[i] is None:
				continue
			try:
				Ni = self.GetAtom(i, 'N')
			except Exception:
				continue
			Hi = H_pos[i]
			for j in range(N):
				if abs(i - j) <= 1:
					continue
				if chains[i] != chains[j]:
					continue
				try:
					Cj = self.GetAtom(j, 'C')
					Oj = self.GetAtom(j, 'O')
				except Exception:
					continue
				r_ON = np.linalg.norm(Oj - Ni)
				r_CH = np.linalg.norm(Cj - Hi)
				r_OH = np.linalg.norm(Oj - Hi)
				r_CN = np.linalg.norm(Cj - Ni)
				if min(r_ON, r_CH, r_OH, r_CN) < 0.001:
					continue
				E = 0.084 * (
					1/r_ON + 1/r_CH
					- 1/r_OH - 1/r_CN) * 332
				if E < -0.5:
					hbond.add((i, j))
		turn3 = [i+3 < N and (i+3, i) in hbond for i in range(N)]
		turn4 = [i+4 < N and (i+4, i) in hbond for i in range(N)]
		turn5 = [i+5 < N and (i+5, i) in hbond for i in range(N)]
		ss = ['L'] * N
		for i in range(N):
			for turn, span in [(turn3,4),(turn4,5),(turn5,6)]:
				if turn[i]:
					for k in range(i, min(i+span, N)):
						if ss[k] == 'L': ss[k] = 'T'
		for i in range(N - 1):
			if turn5[i] and turn5[i + 1]:
				for k in range(i + 1, min(i + 6, N)):
					if ss[k] not in ('H', 'E', 'B'):
						ss[k] = 'I'
		for i in range(N - 1):
			if turn4[i] and turn4[i + 1]:
				for k in range(i + 1, min(i + 5, N)):
					if ss[k] != 'I':
						ss[k] = 'H'
		for i in range(N - 1):
			if turn3[i] and turn3[i + 1]:
				for k in range(i + 1, min(i + 4, N)):
					if ss[k] not in ('H', 'E', 'B'):
						ss[k] = 'G'
		bridge = [None] * N
		for i in range(1, N - 1):
			for k in range(i + 2, N - 1):
				if chains[i] != chains[k]:
					continue
				ap = (
					((i, k) in hbond
					and (k, i) in hbond)
					or (i > 0 and k < N - 1
					and (i - 1, k + 1) in hbond
					and (k - 1, i + 1) in hbond))
				pp = (
					(i > 0 and k < N - 1
					and (i - 1, k) in hbond
					and (k, i + 1) in hbond)
					or (k > 0 and i < N - 1
					and (k - 1, i) in hbond
					and (i, k + 1) in hbond))
				if ap or pp:
					if bridge[i] is None:
						bridge[i] = k
					if bridge[k] is None:
						bridge[k] = i
		for i in range(N):
			if bridge[i] is not None:
				if ss[i] not in ('H', 'G', 'I'):
					ss[i] = 'B'
		for i in range(N - 1):
			if ss[i] == 'B' and ss[i + 1] == 'B':
				k1 = bridge[i]
				k2 = bridge[i + 1]
				if k1 is not None and k2 is not None:
					if abs(k1 - k2) == 1:
						ss[i]  = 'E'
						ss[i + 1] = 'E'
						if ss[k1] not in ('H', 'G', 'I'):
							ss[k1] = 'E'
						if ss[k2] not in ('H', 'G', 'I'):
							ss[k2] = 'E'
		for i in range(2, N - 2):
			if ss[i] != 'L':
				continue
			try:
				m2 = self.GetAtom(i - 2, 'CA')
				ci = self.GetAtom(i,     'CA')
				p2 = self.GetAtom(i + 2, 'CA')
			except Exception:
				continue
			v1   = ci - m2
			v2   = p2 - ci
			n1   = np.linalg.norm(v1)
			n2   = np.linalg.norm(v2)
			if n1 < 0.001 or n2 < 0.001:
				continue
			cos_k = np.dot(v1, v2) / (n1 * n2)
			cos_k = max(-1.0, min(1.0, cos_k))
			kappa = math.acos(cos_k) * 180.0 / math.pi
			if kappa >= 70.0:
				ss[i] = 'S'
		PHI_LO, PHI_HI = -104.0, -46.0
		PSI_LO, PSI_HI =  116.0, 174.0
		ppii = [False] * N
		for i in range(N):
			if ss[i] != 'L':
				continue
			try:
				phi = self.Angle(i, 'PHI')
				psi = self.Angle(i, 'PSI')
			except Exception:
				continue
			ppii[i] = PHI_LO <= phi <= PHI_HI and PSI_LO <= psi <= PSI_HI
		for i in range(N - 2):
			if ppii[i] and ppii[i + 1] and ppii[i + 2]:
				for k in range(i, i + 3):
					if ss[k] == 'L':
						ss[k] = 'P'
		for i in range(N): AAs[i][4] = ss[i]
	def SASA(self, n_points=100, probe_radius=1.4):
		''' Calculate Solvent Accessible Surface Area per residue '''
		VDW = {
			'H':  1.20, 'C':  1.70, 'N':  1.55, 'O':  1.52,
			'S':  1.80, 'SE': 1.90, 'P':  1.80, 'F':  1.47,
			'CL': 1.75, 'BR': 1.85, 'I':  1.98, 'FE': 1.80,
			'ZN': 1.39, 'MG': 1.73, 'CA': 1.97, 'MN': 1.73,
			'CU': 1.40, 'NI': 1.63}
		DEFAULT_VDW = 2.00
		atoms  = self.data['Atoms']
		coords = self.data['Coordinates']
		ids    = sorted(atoms.keys())
		id_map = {ai: ii for ii, ai in enumerate(ids)}
		n      = len(ids)
		c      = coords[np.array(ids)]
		radii = np.array([
			VDW.get(atoms[i][1].upper(),DEFAULT_VDW)+probe_radius for i in ids])
		golden = (1 + np.sqrt(5)) / 2
		pts    = np.arange(n_points)
		theta  = np.arccos(1 - 2 * (pts + 0.5) / n_points)
		phi    = 2 * np.pi * pts / golden
		st  = np.sin(theta)
		sph = np.column_stack([st*np.cos(phi), st*np.sin(phi), np.cos(theta)])
		dm  = np.sqrt(((c[:, None, :] - c[None, :, :])**2).sum(2))
		atom_sasa = np.zeros(n)
		for ii in range(n):
			ri       = radii[ii]
			test_pts = c[ii] + ri * sph
			nbr_mask = (dm[ii] < ri + radii) & (dm[ii] > 0)
			nbrs     = np.where(nbr_mask)[0]
			if len(nbrs) == 0:
				atom_sasa[ii] = 4 * np.pi * ri**2
				continue
			diff_pts = (test_pts[:, None, :] - c[nbrs][None, :, :])
			dist_sq  = (diff_pts**2).sum(2)
			r_sq     = radii[nbrs]**2
			buried   = (dist_sq < r_sq[None, :]).any(axis=1)
			n_exp    = int((~buried).sum())
			atom_sasa[ii] = (n_exp / n_points * 4 * np.pi * ri**2)
		for aa_idx, aa_info in self.data['Amino Acids'].items():
			all_atoms = aa_info[2] + aa_info[3]
			sasa = sum(atom_sasa[id_map[a]] for a in all_atoms if a in id_map)
			self.data['Amino Acids'][aa_idx][6] = round(float(sasa), 5)
	def RotatePose(self, theta=None, u=None, l=None, ori=None):
		''' Rotate and/or translate the full pose rigidly '''
		coords = self.data['Coordinates'].copy()
		if theta is not None and u is not None:
			u = np.array(u, dtype=float)
			mag = np.linalg.norm(u)
			if mag < 1e-10:
				raise Exception('Rotation axis u cannot be a zero vector')
			u = u / mag
			pivot  = coords.mean(axis=0)
			R      = self.Rotation_Matrix(theta, u)
			coords = np.matmul(coords - pivot, R) + pivot
		if l is not None and ori is not None:
			ori      = np.array(ori, dtype=float)
			centroid = coords.mean(axis=0)
			d        = ori - centroid
			mag      = np.linalg.norm(d)
			if mag < 1e-10:
				raise Exception(
					'ori coincides with pose centroid — '
					'translation direction is undefined')
			coords = coords + (d / mag) * l
		self.data['Coordinates'] = coords
