#!/usr/bin/env python3

import os
import json
import math
import copy
import datetime
import numpy as np
from collections import defaultdict

class Pose():
	''' A class that builds and manipulates protein, DNA, and RNA '''
	def __init__(self):
		path, modulename = os.path.split(__file__)
		with open(f'{path}/database.json') as f: database = json.load(f)
		self.aminoacids=database['Amino Acids']
		self.nucleotides=database['Nucleotides']
		self.probbatoms = {'N', '1H', '2H', '3H', 'CA', 'HA', 'C', 'O', 'OXT'}
		self.nucbbatoms = {
			'P'  , 'OP1', 'OP2', "O5'", "C5'", "H5'", "H5''", "C4'",
			"H4'", "O4'", "C3'", "H3'", "C2'", "H2'", "H2''", "C1'",
			"H1'", "O3'", "O2'", "HO2'"}
		self.masses = {
			'H' :1.008  , 'He':4.003  , 'Li':6.941  , 'Be':9.012  ,
			'B' :10.811 , 'C' :12.011 , 'N' :14.007 ,  'O':15.999 ,
			'F' :18.998 , 'Ne':20.180 , 'Na':22.990 , 'Mg':24.305 ,
			'Al':26.982 , 'Si':28.086 , 'P' :30.974 ,  'S':32.066 ,
			'Cl':35.453 , 'Ar':39.948 , 'K' :39.098 , 'Ca':40.078 ,
			'Sc':44.956 , 'Ti':47.867 , 'V' :50.942 , 'Cr':51.996 ,
			'Mn':54.938 , 'Fe':55.845 , 'Co':58.933 , 'Ni':58.693 ,
			'Cu':63.546 , 'Zn':65.38  , 'Ga':69.723 , 'Ge':72.631 ,
			'As':74.922 , 'Se':78.971 , 'Br':79.904 , 'Kr':84.798 ,
			'Rb':84.468 , 'Sr':87.62  , 'Y' :88.906 , 'Zr':91.224 ,
			'Nb':92.906 , 'Mo':95.95  , 'Tc':98.907 , 'Ru':101.07 ,
			'Rh':102.906, 'Pd':106.42 , 'Ag':107.868, 'Cd':112.414,
			'In':114.818, 'Sn':118.711, 'Sb':121.760, 'Te':126.7  ,
			'I' :126.904, 'Xe':131.294, 'Cs':132.905, 'Ba':137.328,
			'La':138.905, 'Ce':140.116, 'Pr':140.908, 'Nd':144.243,
			'Pm':144.913, 'Sm':150.36 , 'Eu':151.964, 'Gd':157.25 ,
			'Tb':158.925, 'Dy':162.500, 'Ho':164.930, 'Er':167.259,
			'Tm':168.934, 'Yb':173.055, 'Lu':174.967, 'Hf':178.49 ,
			'Ta':180.948, 'W' :183.84 , 'Re':186.207, 'Os':190.23 ,
			'Ir':192.217, 'Pt':195.085, 'Au':196.967, 'Hg':200.592,
			'Tl':204.383, 'Pb':207.2  , 'Bi':208.980, 'Po':208.982,
			'At':209.987, 'Rn':222.081, 'Fr':223.020, 'Ra':226.025,
			'Ac':227.028, 'Th':232.038, 'Pa':231.036, 'U' :238.029,
			'Np':237    , 'Pu':244}
		self.data = {'Type':None, 'Energy':0, 'Rg':0, 'Mass':0, 'Size':{},
		'FASTA':{}, 'SS':{}, 'Nucleotides':None, 'Amino Acids':None,
		'Atoms':{}, 'Bonds':{}, 'Coordinates':np.zeros((0, 3))}
	def _isfused(self, SC):
		''' Check if an amino acid's sidechain is fused to the backbone '''
		return self.aminoacids[SC.upper()]['Fused']
	def _compiless(self):
		''' Return per-chain secondary structure dict '''
		if self.data['Amino Acids'] is None: return {}
		ss = {}
		for v in self.data['Amino Acids'].values():
			ss.setdefault(v[1], []).append(v[4])
		ss = {k: ''.join(v) for k, v in ss.items()}
		self.data['SS'] = ss
	def _rotmat(self, theta, u):
		''' Rotate a matrix around axis u by theta angle '''
		ux, uy, uz = u[0], u[1], u[2]
		S = math.sin(math.radians(theta))
		C = math.cos(math.radians(theta))
		R = np.array([
		[C+ux**2*(1-C)   , ux*uy*(1-C)-uz*S, ux*uz*(1-C)+uy*S],
		[uy*ux*(1-C)+uz*S, C+uy**2*(1-C)   , uy*uz*(1-C)-ux*S],
		[uz*ux*(1-C)-uy*S, uz*uy*(1-C)+ux*S, C+uz**2*(1-C)   ]])
		return R
	def _atomiter(self):
		''' Yield (atom, coord, res_idx) for all atoms '''
		src = (self.data['Amino Acids'] or self.data['Nucleotides'])
		At = self.data['Atoms']
		Co = self.data['Coordinates']
		for ri, info in src.items():
			for ai in info[2] + info[3]:
				yield (ai, At[ai]), Co[ai], ri
	def _pdbentry(self, rec, n, a, l, r, c, s, ins, x, y, z, o, t, q, e):
		''' Format a PDB ATOM line '''
		return (
			'{:<6}'.format(rec)
			+ '{:>5} '.format(n)
			+ '{:<4}'.format(a)
			+ '{:<1}'.format(l)
			+ '{:>3}'.format(r)
			+ '{:>2}'.format(c)
			+ '{:>4}'.format(s)
			+ '{:>1}   '.format(ins)
			+ '{:>8.3f}'.format(x)
			+ '{:>8.3f}'.format(y)
			+ '{:>8.3f} '.format(z)
			+ '{:>5.2f} '.format(o)
			+ ('{:>5.2f} '.format(t))[:6]
			+ '{:>10}'.format('')
			+ '{:<2} \n'.format(e))
	def _cifentry(self, rec, n, a, l, r, c, seq, x, y, z, o, t, q, e):
		''' Format a CIF _atom_site line '''
		alt = '.' if l == '' else l
		ch = '?' if q == 0.0 else '{:.3f}'.format(q)
		return ' '.join([
			rec, str(n), e, a, alt, r, c,
			'1', str(seq), '?',
			'{:.3f}'.format(x),
			'{:.3f}'.format(y),
			'{:.3f}'.format(z),
			'{:.2f}'.format(o),
			'{:.2f}'.format(t),
			ch, str(seq), r, c, a, '1']) + '\n'
	def _exportpdb(self, filename, src, ti):
		''' Write PDB file '''
		with open(filename, 'w') as f:
			dt = datetime.date.today()
			f.write('HEADER' + ' '*44
				+ dt.strftime('%d-%b-%Y')
				+ ' '*3 + 'XXXX'
				+ ' '*11 + '\n')
			f.write('EXPDTA    '
				'THEORETICAL MODEL'
				+ ' '*52 + '\n')
			f.write('REMARK 220 REMARK: '
				'MODEL GENERATED BY '
				'SARI SABBAN'
				+ ' '*30 + '\n')
			prev_ch = None
			for atom, coord, ri in self._atomiter():
				info = src[ri]
				ch = info[1]
				if prev_ch is not None and ch != prev_ch: f.write('TER\n')
				f.write(self._pdbentry(
					'ATOM', atom[0]+1,
					atom[1][0], '',
					info[ti], ch, ri+1, '',
					coord[0], coord[1], coord[2],
					atom[1][3], atom[1][4],
					atom[1][2], atom[1][1]))
				prev_ch = ch
			f.write('TER\n')
	def _exportcif(self, filename, src, ti):
		''' Write CIF file '''
		name = os.path.splitext(os.path.basename(filename))[0]
		cols = [
			'_atom_site.group_PDB',
			'_atom_site.id',
			'_atom_site.type_symbol',
			'_atom_site.label_atom_id',
			'_atom_site.label_alt_id',
			'_atom_site.label_comp_id',
			'_atom_site.label_asym_id',
			'_atom_site.label_entity_id',
			'_atom_site.label_seq_id',
			'_atom_site.pdbx_PDB_ins_code',
			'_atom_site.Cartn_x',
			'_atom_site.Cartn_y',
			'_atom_site.Cartn_z',
			'_atom_site.occupancy',
			'_atom_site.B_iso_or_equiv',
			'_atom_site.pdbx_formal_charge',
			'_atom_site.auth_seq_id',
			'_atom_site.auth_comp_id',
			'_atom_site.auth_asym_id',
			'_atom_site.auth_atom_id',
			'_atom_site.pdbx_PDB_model_num']
		with open(filename, 'w') as f:
			f.write(f'data_{name}\n#\n')
			f.write(f'_entry.id   {name}\n#\n')
			f.write("_exptl.method   "
				"'THEORETICAL MODEL'\n#\n")
			f.write("_audit_author.name"
				"          'SARI SABBAN'\n")
			f.write("_audit_author."
				"pdbx_ordinal  1\n#\n")
			f.write('loop_\n')
			for c in cols:
				f.write(c + '\n')
			for atom, coord, ri in self._atomiter():
				info = src[ri]
				f.write(self._cifentry(
					'ATOM', atom[0]+1,
					atom[1][0], '',
					info[ti], info[1], ri+1,
					coord[0], coord[1], coord[2],
					atom[1][3], atom[1][4],
					atom[1][2], atom[1][1]))
			f.write('#\n')
	def _bondtreefused(self, BB, SC):
		''' Construct bond graph for when a sidechain is fused to a backbone '''
		BBb = {int(k): v for k, v in
			copy.deepcopy(self.aminoacids[BB]['Bonds']).items()}
		SCb = {int(k): v for k, v in
			copy.deepcopy(self.aminoacids[SC]['Bonds']).items()}
		length = len(SCb)
		BBb.pop(1)
		nBBb = {}
		for i, a in enumerate(BBb.items()):
			v = a[1]
			v = [x if x==0 else x-1 for x in v]
			nBBb[i] = v
		if BB == 'Backbone' or BB == 'Backbone start':
			n = 3
			nBBb[0][0] = length+1
			BBb = nBBb
		else:
			n = 1
			nBBb[0][0] = length-1
			BBb = nBBb
		for i in reversed(range(len(BBb))):
			if i > n+1:
				newvals = [x if x<=n else x+length-1 for x in BBb[i]]
				newk = i+length-1
				del BBb[i]
				BBb[newk] = newvals
		BBb[n].append(n+1+length)
		for i, (k, v) in enumerate(SCb.items(), start=n+2):
			if k < 0: break
			k = i
			if BB == 'Backbone' or BB == 'Backbone start': v=[x+n+2 for x in v]
			else: v = [x+n+4 if x<0 else x+n+2 for x in v]
			if i == n+2: v.append(n)
			BBb[k] = sorted(v)
		return BBb
	def _bondtreenotfused(self, BB, SC):
		''' Construct amino acid bond graph by adding sidechain to backbone '''
		SC = SC.upper()
		if self._isfused(SC):
			BBb = self._bondtreefused(BB, SC)
			return BBb
		BBb = {int(k): v for k, v in
			copy.deepcopy(self.aminoacids[BB]['Bonds']).items()}
		SCb = {int(k): v for k, v in
			copy.deepcopy(self.aminoacids[SC]['Bonds']).items()}
		length = len(SCb)
		if BB == 'Backbone' or BB == 'Backbone start': n = 4
		else: n = 2
		for i in reversed(range(len(BBb))):
			if i > n+1:
				newvals = [x if x<=n
					else x+length
					for x in BBb[i]]
				newk = i+length
				del BBb[i]
				BBb[newk] = newvals
		BBb[n].append(n + 2 + length)
		for i, (k, v) in enumerate(SCb.items(), start=n+2):
			k = i
			if length != 1:
				v = [x+n+2 for x in v]
				if i == n+2: v.append(n)
			else: v = [x+n+1 for x in v]
			BBb[k] = sorted(v)
		return BBb
	def _bondtree(self, BB, AA, new_chain=False):
		''' Update the pose bond graph when adding a new amino acid '''
		BBb = self._bondtreenotfused(BB, AA)
		BT = self.data['Bonds']
		length = len(BT)
		if length == 0:
			self.data['Bonds'] = BBb
			return
		i_max = max(BT)
		if not new_chain:
			BT[i_max-1] += [i_max+1]
		for i in range(len(BBb)):
			K = i+length
			v = BBb[i]
			V = [x+length for x in v]
			if i == 0 and not new_chain:
				V.append(i_max-1)
			BT[K] = V
		self.data['Bonds'] = BT
	def _downstreamatoms(self, res1, atom1, res2, atom2):
		''' Find atom indices downstream of atom2, on the same chain as res2 '''
		src = (self.data['Amino Acids'] or self.data['Nucleotides'])
		chain = src[res2][1]
		Bi = self.GetAtomIdx(res2, atom2)
		result = set()
		if res1 == res2:
			bb = set(src[res2][2])
			sc = set(src[res2][3])
			if Bi in bb:
				pos = src[res2][2].index(Bi)
				result.update(
					src[res2][2][pos:])
				result.update(src[res2][3])
			else:
				pos = src[res2][3].index(Bi)
				result.update(src[res2][3][pos:])
			for ri, info in src.items():
				if info[1] != chain: continue
				if ri > res2:
					result.update(info[2] + info[3])
		else:
			for ri, info in src.items():
				if info[1] != chain: continue
				if ri >= res2:
					result.update(info[2] + info[3])
		return result
	def _parsepdb(self, filename, chain, model):
		''' Parse ATOM records from a PDB file '''
		with open(filename) as f: raw = f.readlines()
		rows, has_mdl, in_tgt = [], False, False
		found = []
		for line in raw:
			line = line.rstrip()
			if not line: continue
			rec = line[:6].strip()
			if rec == 'MODEL':
				has_mdl = True
				try: mnum = int(line.split()[1])
				except (IndexError, ValueError):
					mnum = len(found) + 1
				found.append(mnum)
				in_tgt = (mnum == model)
				continue
			if rec == 'ENDMDL':
				if in_tgt: break
				in_tgt = False
				continue
			if rec != 'ATOM': continue
			ch = line[21]
			if chain and ch not in chain: continue
			if has_mdl and not in_tgt: continue
			a = line[12:16].strip()
			e = line[76:78].strip()
			if not e:
				s = a.lstrip('0123456789')
				e = s[0] if s else a[0]
			occ = float(line[54:60]) \
				if len(line) >= 60 else 1.0
			bfc = float(line[60:66]) \
				if len(line) >= 66 else 0.0
			rows.append((
				a, line[17:20].strip(),
				ch, int(line[22:26]),
				float(line[30:38]),
				float(line[38:46]),
				float(line[46:54]),
				occ, bfc, e))
		if has_mdl and model not in found:
			raise Exception(
				f'Model {model} not found in '
				f'{filename}. '
				f'Available models: {found}')
		return rows
	def _cifsplit(self, line):
		''' Split a CIF data line respecting quotes '''
		tokens = []
		i, n = 0, len(line)
		while i < n:
			if line[i] in (' ', '\t'):
				i += 1
				continue
			if line[i] in ("'", '"'):
				q = line[i]
				j = line.find(q, i + 1)
				if j == -1: j = n - 1
				tokens.append(line[i+1:j])
				j += 1
				i = j
			else:
				j = i
				while j < n and line[j] not in \
				(' ', '\t'):
					j += 1
				tokens.append(line[i:j])
				i = j
		return tokens
	def _cifcols(self, lines):
		''' Find _atom_site column map and data start '''
		C, ci = {}, 0
		for idx, line in enumerate(lines):
			if line.strip() != 'loop_': continue
			nxt = lines[idx+1].strip() \
				if idx+1 < len(lines) else ''
			if not nxt.startswith('_atom_site.'):
				continue
			i = idx + 1
			while i < len(lines) and \
			lines[i].strip().startswith(
				'_atom_site.'):
				cn = lines[i].strip().split('.')[1]
				C[cn] = ci
				ci += 1
				i += 1
			return C, i
		return C, 0
	def _parsecif(self, filename, chain, model):
		''' Parse ATOM records from a CIF file '''
		with open(filename) as f:
			lines = f.readlines()
		C, start = self._cifcols(lines)
		if not C:
			raise Exception(
				f'No _atom_site loop in '
				f'{filename}')
		i_mdl = C.get('pdbx_PDB_model_num')
		i_alt = C.get('label_alt_id')
		rows, found = [], []
		for line in lines[start:]:
			ln = line.strip()
			if not ln or ln == '#': break
			f = self._cifsplit(ln)
			if f[C['group_PDB']] != 'ATOM': continue
			ch = f[C['auth_asym_id']]
			if chain and ch not in chain: continue
			if i_mdl is not None:
				mnum = int(f[i_mdl])
				if mnum not in found:
					found.append(mnum)
				if mnum != model: continue
			alt = f[i_alt] \
				if i_alt is not None else '.'
			if alt not in ('.','A','1',''): continue
			raw_seq = f[C['auth_seq_id']]
			try: seqid = int(raw_seq)
			except ValueError: continue
			rows.append((
				f[C['auth_atom_id']].strip('"'),
				f[C['auth_comp_id']], ch,
				seqid,
				float(f[C['Cartn_x']]),
				float(f[C['Cartn_y']]),
				float(f[C['Cartn_z']]),
				float(f[C['occupancy']]),
				float(f[C['B_iso_or_equiv']]),
				f[C['type_symbol']]))
		if i_mdl is not None and found \
		and model not in found:
			raise Exception(
				f'Model {model} not found in '
				f'{filename}. Available: {found}')
		return rows
	def _detecttype(self, resnames):
		''' Auto-detect molecule type from residues '''
		aa = {v['Tricode'] for v in
			self.aminoacids.values()
			if 'Tricode' in v}
		if resnames & aa: return 'Protein'
		if resnames & {'DT', 'T'}: return 'DNA'
		if 'U' in resnames: return 'RNA'
		nt = {self.nucleotides[r]['Type']
			for r in resnames
			if r in self.nucleotides}
		return 'RNA' if 'RNA' in nt else 'DNA'
	def _buildresidues(self, residues, sk):
		''' Build Atoms/Aminos/Coords from residues '''
		At, Am, Co = {}, {}, []
		count, ai = 0, 0
		for ch, rn in sk:
			seen = set()
			uniq = [r for r in residues[(ch, rn)]
				if r[0] not in seen
				and not seen.add(r[0])]
			tri = uniq[0][1]
			sym = next((k for k, v in
				self.aminoacids.items()
				if v['Tricode'] == tri), None)
			if sym is None: continue
			BB, SC = [], []
			for r in uniq:
				Co.append([r[4], r[5], r[6]])
				At[count] = [
					r[0], r[9], 0.0, r[7], r[8]]
				(BB if r[0] in self.probbatoms
					else SC).append(count)
				count += 1
			Am[ai] = [
				sym, ch, BB, SC, 'L', tri, 0]
			ai += 1
		return At, Am, np.array(Co)
	def _validatechain(self, At, Am, Co, filename, chain):
		''' Validate backbone atoms and C-N bonds '''
		err = []
		req = {'N', 'CA', 'C'}
		for k in sorted(Am):
			miss = req - {At[a][0]
				for a in Am[k][2]}
			if miss:
				err.append(
					f'  residue {k} ({Am[k][5]})'
					f': missing {sorted(miss)}')
		keys = sorted(Am)
		for ki, kj in zip(keys[:-1], keys[1:]):
			if Am[ki][1] != Am[kj][1]: continue
			ci = next((a for a in Am[ki][2]
				if At[a][0] == 'C'), None)
			ni = next((a for a in Am[kj][2]
				if At[a][0] == 'N'), None)
			if ci is None or ni is None: continue
			d = np.linalg.norm(Co[ci] - Co[ni])
			if d > 2.0:
				err.append(
					f'  {ki} ({Am[ki][5]})'
					f' \u2192 {kj} ({Am[kj][5]})'
					f': C\u2013N={d:.2f}\u00c5')
		if err:
			raise Exception(
				f'Broken chain in {filename}'
				f' chains {chain}:\n'
				+ '\n'.join(err))
	def _buildbonds(self, Am):
		''' Build protein bond tree per chain '''
		cpos = defaultdict(list)
		for i in range(len(Am)):
			cpos[Am[i][1]].append(i)
		prev = None
		for i in range(len(Am)):
			ch = Am[i][1]
			cr = cpos[ch]
			pos = cr.index(i)
			if pos == 0: bb = 'Backbone start'
			elif pos == len(cr)-1:
				bb = 'Backbone end'
			else: bb = 'Backbone middle'
			new = prev is not None and ch != prev
			self._bondtree(
				bb, Am[i][0], new_chain=new)
			prev = ch
	def _importprotein(self, residues, sk, filename, chain):
		''' Populate self.data for protein '''
		At, Am, Co = self._buildresidues(
			residues, sk)
		if not Am:
			raise Exception(
				f'No recognized residues in '
				f'{filename}')
		self._validatechain(At, Am, Co, filename, chain)
		self.data['Coordinates'] = Co
		self.data['Amino Acids'] = Am
		self.data['Atoms'] = At
		self._buildbonds(Am)
		self.CalcCharge()
		self.CalcDSSP()
		self.CalcSASA()
	def _prevres(self, i):
		''' Previous residue on same chain, or None '''
		src = (self.data['Amino Acids'] or self.data['Nucleotides'])
		if i-1 in src and src[i-1][1] == src[i][1]: return i - 1
		return None
	def _nextres(self, i):
		''' Next residue on same chain, or None '''
		src = (self.data['Amino Acids'] or self.data['Nucleotides'])
		if i+1 in src and src[i+1][1] == src[i][1]: return i + 1
		return None
	def _hasatom(self, res, atom):
		''' Check if atom exists in a residue '''
		source = (self.data['Amino Acids'] or self.data['Nucleotides'])
		info = source[res]
		return any(self.data['Atoms'][i][0] == atom for i in info[2] + info[3])
	def _nuctricode(self, resn, mt):
		''' Map residue name to nucleotide tricode '''
		if mt == 'DNA' and resn in ('A','G','C'): return 'D' + resn
		if resn == 'T': return 'DT'
		return resn
	def _addnucleotide(self, db, nr, ai, Co):
		''' Process one nucleotide's atoms/bonds '''
		bbm = db['Backbone Atoms']
		bsm = db['Base Atoms']
		n_bb = len(bbm)
		D = self.data
		bbi, bsi, ltg = [], [], {}
		for li, am in enumerate(bbm + bsm):
			row = nr.get(am[0])
			if row is None:
				ltg[li] = -1
				continue
			D['Atoms'][ai] = [am[0], am[1], am[2], row[7], row[8]]
			Co.append([row[4], row[5], row[6]])
			ltg[li] = ai
			(bsi if li >= n_bb else bbi).append(ai)
			ai += 1
		dbn = {a[0] for a in bbm} | {a[0] for a in bsm}
		for an, row in nr.items():
			if an in dbn: continue
			D['Atoms'][ai] = [an, row[9] or an[0], 0.0, row[7], row[8]]
			Co.append([row[4], row[5], row[6]])
			(bbi if an in self.nucbbatoms else bsi).append(ai)
			ai += 1
		bd = D['Bonds']
		for ks, vl in db['Bonds'].items():
			gi = ltg.get(int(ks), -1)
			if gi == -1: continue
			bd.setdefault(gi, [])
			for lj in vl:
				gj = ltg.get(lj, -1)
				if gj != -1 and gj not in bd[gi]: bd[gi].append(gj)
		return bbi, bsi, ai
	def _phosphobonds(self, nt_ch):
		''' Add O3'-P phosphodiester bonds '''
		At = self.data['Atoms']
		Bd = self.data['Bonds']
		nts = self.data['Nucleotides']
		for ids in nt_ch.values():
			for i in range(len(ids) - 1):
				o3 = next((a for a in nts[ids[i]][2] if At[a][0] == "O3'"),None)
				p = next((a for a in nts[ids[i+1]][2] if At[a][0] == 'P'), None)
				if o3 is None or p is None: continue
				Bd.setdefault(o3, [])
				Bd.setdefault(p, [])
				if p not in Bd[o3]: Bd[o3].append(p)
				if o3 not in Bd[p]: Bd[p].append(o3)
	def _importnucleotide(self, residues, sk, mt):
		''' Populate self.data for DNA/RNA '''
		Co, ai, ni = [], 0, 0
		nt_ch = defaultdict(list)
		for ch, rn in sk:
			resn = residues[(ch, rn)][0][1]
			tri = self._nuctricode(resn, mt)
			if tri not in self.nucleotides: continue
			nr = {r[0]: r for r in residues[(ch, rn)]}
			bbi, bsi, ai = self._addnucleotide(self.nucleotides[tri],nr,ai,Co)
			self.data['Nucleotides'][ni] = [tri[-1], ch, bbi, bsi, tri]
			nt_ch[ch].append(ni)
			ni += 1
		self.data['Coordinates'] = np.array(Co) if Co else np.zeros((0, 3))
		self._phosphobonds(nt_ch)
		self.CalcCharge()
	def _dihedral(self, r1, r2, r3, r4):
		''' Compute dihedral angle from 4 points '''
		u1 = r2 - r1
		u2 = r3 - r2
		u3 = r4 - r3
		mag = np.linalg.norm(u2)
		c12 = np.cross(u1, u2)
		c23 = np.cross(u2, u3)
		a = np.dot(u2, np.cross(c12, c23))
		b = mag * np.dot(c12, c23)
		return math.atan2(a, b) * 180 / math.pi
	def _dihedralpivots(self, res, angle_type, chi_type=None):
		''' Return (res_a, atom_a, res_b, atom_b) for pivot bond of dihedral '''
		at = angle_type.upper()
		mol = self.data['Type']
		nxt = self._nextres(res)
		if mol == 'Protein':
			if at == 'PHI': return res, 'N', res, 'CA'
			elif at == 'PSI': return res, 'CA', res, 'C'
			elif at == 'OMEGA':
				if nxt is None: return None
				return res, 'C', nxt, 'N'
			elif at == 'CHI':
				assert chi_type is not None, 'Protein CHI needs chi_type'
				sym = self.data['Amino Acids'][res][0].upper()
				ca = self.aminoacids[sym]['Chi Angle Atoms'][chi_type-1]
				return res, ca[1], res, ca[2]
			else:
				raise Exception(
					f'Unknown protein angle: '
					f'{angle_type}')
		elif mol in ('DNA', 'RNA'):
			if at == 'ALPHA':     return res, 'P', res, "O5'"
			elif at == 'BETA':    return res, "O5'", res, "C5'"
			elif at == 'GAMMA':   return res, "C5'", res, "C4'"
			elif at == 'DELTA':   return res, "C4'", res, "C3'"
			elif at == 'EPSILON': return res, "C3'", res, "O3'"
			elif at == 'ZETA':
				if nxt is None: return None
				return res, "O3'", nxt, 'P'
			elif at == 'CHI':
				tri = self.data['Nucleotides'][res][4]
				ca = self.nucleotides[tri]['Chi Angle Atoms']
				return res, ca[1], res, ca[2]
			else:
				raise Exception(
					f'Unknown nucleotide angle'
					f': {angle_type}')
		raise Exception(
			'No structure loaded. '
			'Call Import() first')
	def _flip(self, AA):
		''' Flip amino acid 180° on CA H1-H2 axis '''
		p = AA[2]
		AA = AA - p
		H1, H2 = AA[3], AA[4]
		u = np.cross(H1, H2)
		u = u / np.linalg.norm(u)
		TM = np.array([
			[2*u[0]**2-1, 2*u[0]*u[1], 2*u[0]*u[2]],
			[2*u[0]*u[1], 2*u[1]**2-1, 2*u[1]*u[2]],
			[2*u[0]*u[2], 2*u[1]*u[2], 2*u[2]**2-1]])
		return np.matmul(AA, TM) + p
	def _ld(self, AA):
		''' Convert amino acid L to D chirality '''
		return AA * [1, 1, -1]
	def _buildprotein(self, sequence, chain):
		''' Build one protein chain, append to data '''
		is_new = (self.data['Type'] is None or self.data['Amino Acids'] is None)
		if is_new:
			self.data['Type'] = 'Protein'
			self.data['Amino Acids'] = {}
			self.data['Nucleotides'] = None
			self.data['Atoms'] = {}
			self.data['Bonds'] = {}
			self.data['Coordinates'] = \
				np.zeros((0, 3))
		aa_db = self.aminoacids
		Eadj = (0.400, 1.472, 0)
		Oadj = (0.812, 0.940, 0)
		n = len(sequence)
		aa_start = len(self.data['Amino Acids'])
		atom_start = len(self.data['Atoms'])
		new_coords = []
		X, Y, Z = 0, 0, 0
		for i, aa in enumerate(sequence):
			LD = aa.islower()
			last = i == n - 1
			odd = (i % 2) != 0
			if n == 1 or i == 0:
				bb = 'Backbone' if n == 1 else 'Backbone start'
				idx = 6
				flip = False
			else:
				bb = 'Backbone end' if last else 'Backbone middle'
				adj = Eadj if odd else Oadj
				prev = new_coords[-1][-2]
				X = prev[0] + adj[0]
				Y = prev[1] + adj[1]
				Z = prev[2] + adj[2]
				idx = 4
				flip = odd
			T = np.array([X, Y, Z])
			BB = np.array(aa_db[bb]['Vectors']) + T
			SC = np.array(aa_db[aa.upper()]['Vectors']) + T
			AA_co = np.insert(BB, [idx], SC, axis=0)
			if LD: AA_co = self._ld(AA_co)
			if flip: AA_co = self._flip(AA_co)
			if self._isfused(aa): AA_co = np.delete(AA_co, [1], axis=0)
			new_coords.append(AA_co)
		all_co = np.concatenate(new_coords)
		I = atom_start
		for i, aa in enumerate(sequence):
			LD = aa.islower()
			aa_u = aa.upper()
			if n == 1 or i == 0:
				bb = 'Backbone' if n == 1 else 'Backbone start'
				bb_idx = 6
			else:
				bb = 'Backbone end' if i == n-1 else 'Backbone middle'
				bb_idx = 4
			bb_atoms = aa_db[bb][
				'Backbone Atoms'][:bb_idx]
			if self._isfused(aa):
				bb_atoms = [b for j, b in enumerate(bb_atoms) if j != 1]
			sc_atoms = aa_db[aa_u]['Sidechain Atoms']
			tail = aa_db[bb]['Backbone Atoms'][bb_idx:]
			full = bb_atoms + sc_atoms + tail
			BBi, SCi = [], []
			for v in full:
				self.data['Atoms'][I] = [v[0], v[1], v[2], v[3], v[4]]
				if v[0] in self.probbatoms: BBi.append(I)
				else: SCi.append(I)
				I += 1
			tri = aa_db[aa_u]['Tricode']
			if LD: tri = 'D' + tri[1:]
			ai = aa_start + i
			self.data['Amino Acids'][ai] = [aa, chain, BBi, SCi, 'L', tri, 0]
		self.data['Coordinates'] = np.append(
			self.data['Coordinates'], all_co, axis=0)
		for i, aa in enumerate(sequence):
			ai = aa_start + i
			if n == 1 or i == 0:
				bb = 'Backbone' if n == 1 else 'Backbone start'
			else:
				bb = 'Backbone end' if i == n-1 else 'Backbone middle'
			new_ch = (i == 0 and aa_start > 0)
			self._bondtree(bb, aa, new_chain=new_ch)
	def _buildnucleotide(self, sequence, fmt, chains=None):
		''' Build DNA or RNA (single or double strand) '''
		sequence = sequence.upper()
		N = len(sequence)
		if fmt == 'DNA':
			comp = {'A':'T', 'T':'A', 'G':'C', 'C':'G'}
			tri = {'A':'DA', 'T':'DT', 'G':'DG', 'C':'DC'}
			rise, twist = 3.375, 36.0
		else:
			comp = {'A':'U', 'U':'A', 'G':'C', 'C':'G'}
			tri = {'A':'A', 'U':'U', 'G':'G', 'C':'C'}
			rise, twist = 2.548, 32.7
		def Rz(deg):
			t = math.radians(deg)
			c, s = math.cos(t), math.sin(t)
			return np.array([
				[c, -s, 0.],
				[s, c, 0.],
				[0., 0., 1.]])
		Rflip = np.diag([1.0, -1.0, -1.0])
		self.data = {
			'Type': fmt, 'Energy': 0,
			'Rg': 0, 'Mass': 0, 'Size': {},
			'FASTA': {}, 'SS': {},
			'Nucleotides': {},
			'Amino Acids': None,
			'Atoms': {}, 'Bonds': {},
			'Coordinates': np.zeros((0, 3))}
		Co, ai, ni = [], 0, 0
		nt_ch = defaultdict(list)
		def add_nt(tricode, chain, k, flip):
			nonlocal ai, ni
			db = self.nucleotides[tricode]
			vecs = np.array(db['Vectors'])
			bbm = db['Backbone Atoms']
			bsm = db['Base Atoms']
			n_bb = len(bbm)
			R = Rz(-k * twist)
			T = np.array([0., 0., -k * rise])
			if flip:
				tr = (vecs @ Rflip.T) @ R.T + T
			else:
				tr = vecs @ R.T + T
			ltg = {}
			bbi, bsi = [], []
			for li in range(n_bb):
				am = bbm[li]
				self.data['Atoms'][ai] = [am[0], am[1], am[2], 1.0, 0.0]
				Co.append(tr[li])
				ltg[li] = ai
				bbi.append(ai)
				ai += 1
			for li2, am in enumerate(bsm):
				li = n_bb + li2
				self.data['Atoms'][ai] = [am[0], am[1], am[2], 1.0, 0.0]
				Co.append(tr[li])
				ltg[li] = ai
				bsi.append(ai)
				ai += 1
			bd = self.data['Bonds']
			for ks, vl in db['Bonds'].items():
				gi = ltg.get(int(ks), -1)
				if gi == -1: continue
				bd.setdefault(gi, [])
				for lj in vl:
					gj = ltg.get(lj, -1)
					if gj != -1 and gj not in bd[gi]:
						bd[gi].append(gj)
			sym = tricode[-1]
			self.data['Nucleotides'][ni] = [sym, chain, bbi, bsi, tricode]
			nt_ch[chain].append(ni)
			ni += 1
		if chains is None:
			chains = ['A', 'B']
		chain_a = chains[0]
		for i, base in enumerate(sequence):
			add_nt(tri[base], chain_a, i, False)
		if len(chains) > 1:
			chain_b = chains[1]
			comp_seq = ''.join(
				comp[b]
				for b in reversed(sequence))
			for j, base in enumerate(comp_seq):
				add_nt(tri[base], chain_b,
					N - 1 - j, True)
		self.data['Coordinates'] = np.array(Co)
		self._phosphobonds(nt_ch)
	def _kabsch(self, P, Q):
		''' Kabsch optimal rotation alignment '''
		Pc = P.mean(0)
		Qc = Q.mean(0)
		H = (P - Pc).T @ (Q - Qc)
		U, S, Vt = np.linalg.svd(H)
		d = np.sign(np.linalg.det(Vt.T @ U.T))
		R = Vt.T @ np.diag([1.0, 1.0, d]) @ U.T
		return R, Qc, Pc
	def _rebuildprotein(self, sequence, D_AA):
		''' Rebuild protein from internal coords '''
		AAs = self.data['Amino Acids']
		N = len(AAs)
		fasta = self.data['FASTA']
		if sequence is None:
			sequence = fasta
		if isinstance(sequence, str) \
		and len(fasta) > 1:
			raise Exception(
				'Multi-chain protein requires '
				'sequence as dict, e.g. '
				'{"A":"SEQ1", "B":"SEQ2"}')
		if isinstance(sequence, dict):
			full_seq = dict(fasta)
			full_seq.update(sequence)
			sequence = full_seq
		if isinstance(sequence, dict):
			for ch in sequence:
				if ch in fasta \
				and len(sequence[ch]) \
				!= len(fasta[ch]):
					raise Exception(
						f'Chain {ch}: sequence '
						f'length '
						f'{len(sequence[ch])} '
						f'does not match '
						f'original '
						f'{len(fasta[ch])}')
		elif isinstance(sequence, str):
			ch0 = sorted(fasta.keys())[0]
			if len(sequence) != len(fasta[ch0]):
				raise Exception(
					f'Sequence length '
					f'{len(sequence)} does not '
					f'match original '
					f'{len(fasta[ch0])}')
		orig_coords = {}
		for i in range(N):
			info = AAs[i]
			for ai in info[2] + info[3]:
				aname = self.data['Atoms'][ai][0]
				orig_coords[(i, aname)] = \
					self.data[
						'Coordinates'][ai].copy()
		def _bb_frame(coords, i, src):
			info = src[i]
			n_i = next(a for a in info[2]
				if self.data['Atoms'][a][0]
				== 'N')
			ca_i = next(a for a in info[2]
				if self.data['Atoms'][a][0]
				== 'CA')
			c_i = next(a for a in info[2]
				if self.data['Atoms'][a][0]
				== 'C')
			n = coords[n_i].copy()
			ca = coords[ca_i].copy()
			c = coords[c_i].copy()
			e1 = ca - n
			e1 = e1 / np.linalg.norm(e1)
			v = c - n
			e2 = v - np.dot(v, e1) * e1
			nm = np.linalg.norm(e2)
			if nm < 1e-10: return None, None
			e2 = e2 / nm
			F = np.array(
				[e1, e2, np.cross(e1, e2)])
			return F, n
		self.data = {
			'Type': None, 'Energy': 0,
			'Rg': 0, 'Mass': 0, 'Size': {},
			'FASTA': {}, 'SS': {},
			'Nucleotides': None,
			'Amino Acids': None,
			'Atoms': {}, 'Bonds': {},
			'Coordinates': np.zeros((0, 3))}
		if isinstance(sequence, dict):
			for ch, seq in sorted(
			sequence.items()):
				self._buildprotein(seq, ch)
		else:
			ch0 = sorted(fasta.keys())[0]
			self._buildprotein(sequence, ch0)
		AAs2 = self.data['Amino Acids']
		coords = self.data['Coordinates']
		for i in range(len(AAs2)):
			has_orig = (
				(i, 'N') in orig_coords
				and (i, 'CA') in orig_coords
				and (i, 'C') in orig_coords)
			if not has_orig: continue
			F_new, ori_new = _bb_frame(
				coords, i, AAs2)
			if F_new is None: continue
			on = orig_coords[(i, 'N')]
			oca = orig_coords[(i, 'CA')]
			oc = orig_coords[(i, 'C')]
			e1 = oca - on
			e1 = e1 / np.linalg.norm(e1)
			v = oc - on
			e2 = v - np.dot(v, e1) * e1
			nm = np.linalg.norm(e2)
			if nm < 1e-10: continue
			e2 = e2 / nm
			F_orig = np.array(
				[e1, e2, np.cross(e1, e2)])
			F_orig_inv = F_orig.T
			for ai in AAs2[i][2] + AAs2[i][3]:
				aname = self.data['Atoms'][ai][0]
				if (i, aname) in orig_coords:
					coords[ai] = \
						orig_coords[(i, aname)]
				else:
					local = F_new @ (
						coords[ai] - ori_new)
					coords[ai] = \
						on + F_orig_inv @ local
		self.data['Coordinates'] = coords
		self.CalcCharge()
		self.CalcDSSP()
		self.CalcSASA()
		if D_AA:
			self.data['Coordinates'] *= [1, 1, -1]
			N2 = len(self.data['Amino Acids'])
			for i in range(N2):
				aa = self.data['Amino Acids'][i]
				aa[0] = aa[0].lower()
				aa[5] = 'D' + aa[5][1:]
	def _rebuildnucleotide(self, sequence, _mutated):
		''' Rebuild DNA/RNA from internal coords '''
		fmt = self.data['Type']
		nts = self.data['Nucleotides']
		N = len(nts)
		fasta = self.data['FASTA']
		first_ch = sorted(fasta.keys())[0]
		if sequence is None:
			seq_a = fasta[first_ch]
		else:
			seq_a = sequence
		orig_len = len(fasta[first_ch])
		if len(seq_a) != orig_len:
			raise Exception(
				f'Sequence length '
				f'{len(seq_a)} does not match '
				f'original {orig_len}')
		old_syms = [nts[i][0]
			for i in range(N)]
		ALPHAs, BETAs, GAMMAs = {}, {}, {}
		DELTAs, EPSILONs, ZETAs = {}, {}, {}
		CHIs = {}
		aPO5C5, aO5C5C4 = {}, {}
		aC5C4C3, aC4C3O3 = {}, {}
		aC3O3P, aO3PO5 = {}, {}
		bPO5, bO5C5, bC5C4 = {}, {}, {}
		bC4C3, bC3O3, bO3P = {}, {}, {}
		for i in range(N):
			prv = self._prevres(i)
			nxt = self._nextres(i)
			has_P = self._hasatom(i, 'P')
			if prv is not None \
			and self._hasatom(prv, "O3'") \
			and has_P:
				ALPHAs[i] = self.GetDihedral(i, 'ALPHA')
			if has_P:
				BETAs[i] = self.GetDihedral(i, 'BETA')
			GAMMAs[i] = self.GetDihedral(i, 'GAMMA')
			DELTAs[i] = self.GetDihedral(i, 'DELTA')
			if nxt is not None and self._hasatom(nxt, 'P'):
				EPSILONs[i] = self.GetDihedral(i, 'EPSILON')
				ZETAs[i] = self.GetDihedral(i, 'ZETA')
			CHIs[i] = self.GetDihedral(i, 'CHI')
			if has_P:
				aPO5C5[i] = self.GetAngle(i, 'P', i, "O5'", i, "C5'")
				bPO5[i] = self.GetDistance(i, 'P', i, "O5'")
			aO5C5C4[i] = self.GetAngle(i, "O5'", i, "C5'", i, "C4'")
			bO5C5[i] = self.GetDistance(i, "O5'", i, "C5'")
			aC5C4C3[i] = self.GetAngle(i, "C5'", i, "C4'", i, "C3'")
			bC5C4[i] = self.GetDistance(i, "C5'", i, "C4'")
			aC4C3O3[i] = self.GetAngle(i, "C4'", i, "C3'", i, "O3'")
			bC4C3[i] = self.GetDistance(i, "C4'", i, "C3'")
			bC3O3[i] = self.GetDistance(i, "C3'", i, "O3'")
			if nxt is not None:
				aC3O3P[i] = self.GetAngle(i, "C3'", i, "O3'", nxt, 'P')
				aO3PO5[i] = self.GetAngle(i, "O3'", nxt, 'P', nxt, "O5'")
				bO3P[i] = self.GetDistance(i, "O3'", nxt, 'P')
		ref_C1 = []
		for i in range(N):
			if self._hasatom(i, "C1'"):
				ref_C1.append(self.GetAtomCoord(i, "C1'").copy())
			else:
				ref_C1.append(None)
		def _local_frame(c4, c3, c5):
			e1 = c3 - c4
			e1 = e1 / np.linalg.norm(e1)
			v = c5 - c4
			e2 = v - np.dot(v, e1) * e1
			n = np.linalg.norm(e2)
			if n < 1e-10: return None
			e2 = e2 / n
			return np.array([e1, e2, np.cross(e1, e2)])
		ring_local = {}
		bb_skip = {"P", "O5'", "C5'", "C4'", "C3'", "O3'"}
		for i in range(N):
			if not (self._hasatom(i, "C4'")
			and self._hasatom(i, "C3'")
			and self._hasatom(i, "C5'")):
				continue
			c4 = self.GetAtomCoord(i, "C4'").copy()
			c3 = self.GetAtomCoord(i, "C3'").copy()
			c5 = self.GetAtomCoord(i, "C5'").copy()
			F = _local_frame(c4, c3, c5)
			if F is None: continue
			info = nts[i]
			saved = {}
			for ai in info[2] + info[3]:
				aname = self.data['Atoms'][ai][0]
				if aname in bb_skip: continue
				pos = self.data['Coordinates'][ai].copy()
				saved[aname] = F @ (pos - c4)
			ring_local[i] = saved
		orig_chains = sorted(set(
			v[1] for v in nts.values()))
		self._buildnucleotide(
			seq_a, fmt, chains=orig_chains)
		self.CalcCharge()
		nts2 = self.data['Nucleotides']
		if _mutated is None:
			new_syms = [nts2[i][0]
				for i in range(len(nts2))]
			_mutated = {i for i in range(
				min(N, len(nts2)))
				if old_syms[i] != new_syms[i]}
		def _sugarframe(mi):
			info = nts2[mi]
			ai_o4 = next((a for a in info[2]
				if self.data['Atoms'][a][0]
				== "O4'"), None)
			ai_c1 = next((a for a in info[2]
				if self.data['Atoms'][a][0]
				== "C1'"), None)
			ai_c2 = next((a for a in info[2]
				if self.data['Atoms'][a][0]
				== "C2'"), None)
			if None in (ai_o4, ai_c1, ai_c2):
				return None, None
			co = self.data['Coordinates']
			c1 = co[ai_c1].copy()
			o4 = co[ai_o4].copy()
			c2 = co[ai_c2].copy()
			e1 = o4 - c1
			nm = np.linalg.norm(e1)
			if nm < 1e-10: return None, None
			e1 = e1 / nm
			v = c2 - c1
			e2 = v - np.dot(v, e1) * e1
			nm2 = np.linalg.norm(e2)
			if nm2 < 1e-10: return None, None
			e2 = e2 / nm2
			F = np.array(
				[e1, e2, np.cross(e1, e2)])
			return F, c1
		build_base_local = {}
		for mi in _mutated:
			if mi >= len(nts2): continue
			Fb, c1b = _sugarframe(mi)
			if Fb is None: continue
			saved = {}
			for ai in nts2[mi][3]:
				aname = self.data[
					'Atoms'][ai][0]
				saved[aname] = Fb @ (
					self.data['Coordinates'][ai]
					- c1b)
			build_base_local[mi] = saved
		for i in range(N):
			if i in ALPHAs:
				self.RotateDihedral(i, ALPHAs[i], 'ALPHA')
			if i in BETAs:
				self.RotateDihedral(i, BETAs[i], 'BETA')
			self.RotateDihedral(i, GAMMAs[i], 'GAMMA')
			self.RotateDihedral(i, DELTAs[i], 'DELTA')
			self.RotateDihedral(i, CHIs[i], 'CHI')
			if i in bPO5:
				self.AdjustDistance(i, 'P', i, "O5'", bPO5[i])
			if i in bO5C5:
				self.AdjustDistance(i, "O5'", i, "C5'", bO5C5[i])
			if i in bC5C4:
				self.AdjustDistance(i, "C5'", i, "C4'", bC5C4[i])
			if i in bC4C3:
				self.AdjustDistance(i, "C4'", i, "C3'", bC4C3[i])
			if i in bC3O3:
				self.AdjustDistance(i, "C3'", i, "O3'", bC3O3[i])
			if i in aPO5C5:
				cur = self.GetAngle(i, 'P', i, "O5'", i, "C5'")
				self.AdjustAngle(i, 'P', i, "O5'", i, "C5'", cur - aPO5C5[i])
			if i in aO5C5C4:
				cur = self.GetAngle(i, "O5'", i, "C5'", i, "C4'")
				self.AdjustAngle(i, "O5'", i, "C5'", i, "C4'", cur - aO5C5C4[i])
			if i in aC5C4C3:
				cur = self.GetAngle(i, "C5'", i, "C4'", i, "C3'")
				self.AdjustAngle(i, "C5'", i, "C4'", i, "C3'", cur - aC5C4C3[i])
			if i in aC4C3O3:
				cur = self.GetAngle(i, "C4'", i, "C3'", i, "O3'")
				self.AdjustAngle(i, "C4'", i, "C3'", i, "O3'", cur - aC4C3O3[i])
			nxt = self._nextres(i)
			if nxt is not None:
				if i in EPSILONs:
					self.RotateDihedral(i, EPSILONs[i], 'EPSILON')
				if i in ZETAs:
					self.RotateDihedral(i, ZETAs[i], 'ZETA')
				if i in bO3P:
					self.AdjustDistance(i, "O3'", nxt, 'P', bO3P[i])
				if i in aC3O3P:
					cur = self.GetAngle(i, "C3'", i, "O3'", nxt, 'P')
					self.AdjustAngle(
						i, "C3'", i, "O3'", nxt, 'P', cur - aC3O3P[i])
				if i in aO3PO5:
					cur = self.GetAngle(i, "O3'", nxt, 'P', nxt, "O5'")
					self.AdjustAngle(
						i, "O3'", nxt, 'P', nxt, "O5'", cur - aO3PO5[i])
		coords = self.data['Coordinates']
		for i in range(N):
			if i not in ring_local: continue
			if not (self._hasatom(i, "C4'")
			and self._hasatom(i, "C3'")
			and self._hasatom(i, "C5'")):
				continue
			c4 = self.GetAtomCoord(
				i, "C4'").copy()
			c3 = self.GetAtomCoord(
				i, "C3'").copy()
			c5 = self.GetAtomCoord(
				i, "C5'").copy()
			F = _local_frame(c4, c3, c5)
			if F is None: continue
			Finv = F.T
			saved = ring_local[i]
			if i in _mutated:
				restore = nts2[i][2]
			else:
				restore = nts2[i][2] + nts2[i][3]
			for ai in restore:
				aname = self.data[
					'Atoms'][ai][0]
				if aname in saved:
					coords[ai] = \
						c4 + Finv @ saved[aname]
		self.data['Coordinates'] = coords
		coords = self.data['Coordinates']
		for ch in set(
		v[1] for v in nts2.values()):
			ref_pts, new_pts, aids = [], [], []
			for i in range(N):
				if nts2[i][1] != ch: continue
				if ref_C1[i] is None: continue
				ref_pts.append(ref_C1[i])
				new_pts.append(self.GetAtomCoord(i, "C1'").copy())
				for ai in (
				nts2[i][2] + nts2[i][3]):
					if ai not in aids:
						aids.append(ai)
			if len(ref_pts) < 3: continue
			P = np.array(ref_pts, dtype=float)
			Q = np.array(new_pts, dtype=float)
			R, Qc, Pc = self._kabsch(P, Q)
			for ai in aids:
				coords[ai] = \
					(coords[ai] - Qc) @ R + Pc
		self.data['Coordinates'] = coords
		coords = self.data['Coordinates']
		for mi in _mutated:
			if mi not in build_base_local:
				continue
			Fr, c1r = _sugarframe(mi)
			if Fr is None: continue
			Fri = Fr.T
			bsaved = build_base_local[mi]
			for ai in nts2[mi][3]:
				aname = self.data[
					'Atoms'][ai][0]
				if aname in bsaved:
					coords[ai] = \
						c1r + Fri @ bsaved[aname]
		self.data['Coordinates'] = coords
		for mi in _mutated:
			if mi >= len(nts2): continue
			if mi not in CHIs: continue
			cur = self.GetDihedral(mi, 'CHI')
			target = CHIs[mi]
			tri = nts2[mi][4]
			ca = self.nucleotides[tri][
				'Chi Angle Atoms']
			piv_a = self.GetAtomIdx(mi, ca[1])
			piv_b = self.GetAtomIdx(mi, ca[2])
			ori = coords[piv_b].copy()
			u = coords[piv_a] - coords[piv_b]
			mag = np.linalg.norm(u)
			if mag < 1e-10: continue
			u = u / mag
			RM0 = self._rotmat(-cur, u)
			RM1 = self._rotmat(target, u)
			for ai in nts2[mi][3]:
				v = coords[ai] - ori
				v = np.matmul(v, RM0)
				v = np.matmul(v, RM1)
				coords[ai] = v + ori
		self.data['Coordinates'] = coords
	def _update(self):
		''' Update cached properties after structural changes '''
		self.CalcMass()
		self.CalcSize()
		self.CalcFASTA()
		self.CalcRg()
		if self.data['Type'] == 'Protein': self.CalcDSSP()
		else: self.data['SS'] = {}
	def CalcMass(self):
		''' Calculate mass of peptide in Da'''
		mass = round(sum(self.masses.get(x, 0.0) for x in self.GetAtomList()),3)
		self.data['Mass'] = mass
	def CalcSize(self):
		''' Calculate length of each chain '''
		source = (self.data['Amino Acids']
			or self.data['Nucleotides'])
		if not source:
			self.data['Size'] = {}
			return
		size = {}
		for v in source.values():
			size[v[1]] = size.get(v[1], 0) + 1
		self.data['Size'] = size
	def CalcFASTA(self):
		''' Return per-chain FASTA dict '''
		source = (self.data['Amino Acids'] or self.data['Nucleotides'])
		if not source:
			self.data['FASTA'] = {}
			return
		fasta = {}
		for v in source.values(): fasta.setdefault(v[1], []).append(v[0])
		self.data['FASTA'] = {k: ''.join(v) for k, v in fasta.items()}
	def CalcRg(self):
		''' Calculate the radius of gyration of a peptide '''
		mass  = np.array([self.masses.get(e, 0.0) for e in self.GetAtomList()])
		tmass = mass.sum()
		if tmass == 0: raise ZeroDivisionError('No atoms in pose')
		coord = self.data['Coordinates']
		xm    = coord * mass[:, np.newaxis]
		rr    = np.sum(coord * xm)
		mm    = np.sum((xm.sum(0) / tmass) ** 2)
		rg = round(math.sqrt(max(0.0, rr/tmass - mm)), 3)
		self.data['Rg'] = rg
	def CalcCharge(self, iterations=6):
		''' Calculate Gasteiger-Marsili partial charges to all atoms '''
		PARAMS = {
			'C3': (7.98,  9.18,  1.88),
			'C2': (8.79,  9.32,  1.51),
			'C1': (10.39, 9.45,  0.73),
			'H':  (7.17,  6.24, -0.56),
			'O3': (14.18, 12.92, 1.39),
			'O2': (17.07, 13.79, 0.47),
			'N3': (11.54, 10.82, 1.36),
			'N2': (12.87, 11.15, 0.85),
			'S':  (10.14,  9.13, 1.38),
			'Se': (9.00,   8.00, 1.10)}
		ids  = sorted(self.data['Atoms'].keys())
		crds = self.data['Coordinates']
		els  = [self.data['Atoms'][i][1].upper() for i in ids]
		c = crds[np.array(ids)]
		dm = np.sqrt(((c[:, None, :] - c[None, :, :]) ** 2).sum(2))
		is_H = np.array([e == 'H'         for e in els])
		is_S = np.array([e in ('S', 'SE') for e in els])
		heavy_thresh = np.full((len(ids), len(ids)), 1.9)
		h_mask = is_H[:, None] | is_H[None, :]
		s_mask = is_S[:, None] | is_S[None, :]
		heavy_thresh[h_mask] = 1.3
		heavy_thresh[s_mask] = 2.1
		bond_mask = (dm < heavy_thresh) & (dm > 0.0)
		bonds = {i: [] for i in ids}
		for ii, jj in np.argwhere(bond_mask): bonds[ids[ii]].append(ids[jj])
		heavy = ~is_H
		short = (dm < 1.42) & (dm > 0)
		sp2_mask = short & heavy[:, None] & heavy[None, :]
		sp2 = {ids[ii] for ii in np.where(sp2_mask.any(axis=1))[0]}
		def _types(ii, i):
			''' Classifies each atom into a Gasteiger atom type '''
			el = els[ii]
			if el == 'H':  return 'H'
			if el == 'S':  return 'S'
			if el == 'SE': return 'Se'
			nb    = len(bonds[i])
			isp2  = i in sp2
			if el == 'C':
				if isp2:    return 'C2'
				if nb <= 2: return 'C1'
				return 'C3'
			if el == 'N': return 'N2' if isp2 else 'N3'
			if el == 'O': return 'O2' if isp2 else 'O3'
			return 'C3'
		charges = {i: self.data['Atoms'][i][2] for i in ids}
		atype   = {i: PARAMS[_types(ii, i)] for ii, i in enumerate(ids)}
		for n in range(iterations):
			damp = 1.0 / (2 ** (n + 1))
			chi = {i: a + q*(b + c*q) for i in ids
				for a, b, c in [atype[i]] for q in [charges[i]]}
			delta = {i: 0.0 for i in ids}
			for i in ids:
				for j in bonds[i]:
					if j <= i: continue
					if chi[j] >= chi[i]: donor, acceptor = i, j
					else: donor, acceptor = j, i
					a, b, c = atype[donor]
					ip = a + b + c
					if ip == 0: continue
					dq = damp * (chi[acceptor] - chi[donor]) / ip
					delta[donor]    += dq
					delta[acceptor] -= dq
			for i in ids: charges[i] += delta[i]
		for i in ids: self.data['Atoms'][i][2] = round(charges[i], 4)
	def CalcDSSP(self):
		''' Assign secondary structures to each amino acid '''
		if self.data['Amino Acids'] is None:
			raise Exception('No protein loaded. ' 'Call Import() first')
		N = len(self.data['Amino Acids'])
		AAs      = self.data['Amino Acids']
		chains   = [AAs[i][1]         for i in range(N)]
		tricodes = [AAs[i][5].upper() for i in range(N)]
		H_pos = [None] * N
		for i in range(N):
			if tricodes[i] == 'PRO': continue
			if i == 0 or chains[i] != chains[i-1]: continue
			if self._hasatom(i, 'H'): H_pos[i] = self.GetAtomCoord(i, 'H')
			elif self._hasatom(i, '1H'): H_pos[i] = self.GetAtomCoord(i, '1H')
			elif (self._hasatom(i, 'N')
			and self._hasatom(i-1, 'C')
			and self._hasatom(i-1, 'O')):
				Ni = self.GetAtomCoord(i, 'N')
				Cp = self.GetAtomCoord(i-1, 'C')
				Op = self.GetAtomCoord(i-1, 'O')
				co = Cp - Op
				nm = np.linalg.norm(co)
				if nm > 0.001: H_pos[i] = Ni + (co / nm)
		hbond = set()
		for i in range(N):
			if H_pos[i] is None: continue
			Ni = self.GetAtomCoord(i, 'N')
			Hi = H_pos[i]
			for j in range(N):
				if abs(i - j) <= 1: continue
				if chains[i] != chains[j]: continue
				if not self._hasatom(j, 'O'): continue
				Cj = self.GetAtomCoord(j, 'C')
				Oj = self.GetAtomCoord(j, 'O')
				r_ON = np.linalg.norm(Oj - Ni)
				r_CH = np.linalg.norm(Cj - Hi)
				r_OH = np.linalg.norm(Oj - Hi)
				r_CN = np.linalg.norm(Cj - Ni)
				if min(r_ON, r_CH, r_OH, r_CN) < 0.001: continue
				E = 0.084 * (1/r_ON + 1/r_CH - 1/r_OH - 1/r_CN) * 332
				if E < -0.5: hbond.add((i, j))
		turn3 = [i+3 < N and (i+3, i) in hbond for i in range(N)]
		turn4 = [i+4 < N and (i+4, i) in hbond for i in range(N)]
		turn5 = [i+5 < N and (i+5, i) in hbond for i in range(N)]
		ss = ['L'] * N
		for i in range(N):
			for turn, span in [(turn3,4),(turn4,5),(turn5,6)]:
				if turn[i]:
					for k in range(i, min(i+span, N)):
						if ss[k] == 'L': ss[k] = 'T'
		for i in range(N - 1):
			if turn5[i] and turn5[i + 1]:
				for k in range(i + 1, min(i + 6, N)):
					if ss[k] not in ('H', 'E', 'B'): ss[k] = 'I'
		for i in range(N - 1):
			if turn4[i] and turn4[i + 1]:
				for k in range(i + 1, min(i + 5, N)):
					if ss[k] != 'I': ss[k] = 'H'
		for i in range(N - 1):
			if turn3[i] and turn3[i + 1]:
				for k in range(i + 1, min(i + 4, N)):
					if ss[k] not in ('H', 'E', 'B'): ss[k] = 'G'
		bridges = set()
		for i in range(1, N - 1):
			for k in range(i + 2, N - 1):
				if chains[i] != chains[k]: continue
				ap = (
					((i, k) in hbond
					and (k, i) in hbond)
					or (i > 0 and k < N - 1
					and (i - 1, k + 1) in hbond
					and (k - 1, i + 1) in hbond))
				pp = (
					(i > 0 and k < N - 1
					and (i - 1, k) in hbond
					and (k, i + 1) in hbond)
					or (k > 0 and i < N - 1
					and (k - 1, i) in hbond
					and (i, k + 1) in hbond))
				if ap or pp: bridges.add((i, k))
		br_at = defaultdict(set)
		for i, k in bridges:
			br_at[i].add(k)
			br_at[k].add(i)
		for r in br_at:
			if ss[r] not in ('H', 'G', 'I'): ss[r] = 'B'
		changed = True
		while changed:
			changed = False
			for i in range(N - 1):
				if (ss[i] not in ('B', 'E')
				or ss[i+1] not in ('B', 'E')): continue
				for k1 in br_at.get(i, []):
					for k2 in br_at.get(i+1, []):
						if abs(k1 - k2) != 1: continue
						for r in (i, i+1, k1, k2):
							if ss[r] in ('H', 'G', 'I'): continue
							if ss[r] != 'E':
								ss[r] = 'E'
								changed = True
		for i in range(2, N - 2):
			if ss[i] != 'L': continue
			if (chains[i-2] != chains[i]
			or chains[i+2] != chains[i]): continue
			m2 = self.GetAtomCoord(i - 2, 'CA')
			ci = self.GetAtomCoord(i,     'CA')
			p2 = self.GetAtomCoord(i + 2, 'CA')
			v1 = ci - m2
			v2 = p2 - ci
			n1 = np.linalg.norm(v1)
			n2 = np.linalg.norm(v2)
			if n1 < 0.001 or n2 < 0.001: continue
			cos_k = np.dot(v1, v2) / (n1 * n2)
			cos_k = max(-1.0, min(1.0, cos_k))
			kappa = math.acos(cos_k) * 180.0 / math.pi
			if kappa >= 70.0: ss[i] = 'S'
		PHI_LO, PHI_HI = -104.0, -46.0
		PSI_LO, PSI_HI =  116.0, 174.0
		ppii = [False] * N
		for i in range(N):
			if ss[i] != 'L': continue
			phi = self.GetDihedral(i, 'PHI')
			psi = self.GetDihedral(i, 'PSI')
			ppii[i] = PHI_LO <= phi <= PHI_HI and PSI_LO <= psi <= PSI_HI
		for i in range(N - 2):
			if ppii[i] and ppii[i + 1] and ppii[i + 2]:
				for k in range(i, i + 3):
					if ss[k] == 'L': ss[k] = 'P'
		for i in range(N): AAs[i][4] = ss[i]
		self._compiless()
	def CalcSASA(self, n_points=100, probe_radius=1.4):
		''' Calculate SASA per residue '''
		if self.data['Amino Acids'] is None:
			raise Exception(
				'No protein loaded. '
				'Call Import() first')
		VDW = {
			'H':  1.20, 'C':  1.70, 'N':  1.55, 'O':  1.52,
			'S':  1.80, 'SE': 1.90, 'P':  1.80, 'F':  1.47,
			'CL': 1.75, 'BR': 1.85, 'I':  1.98, 'FE': 1.80,
			'ZN': 1.39, 'MG': 1.73, 'CA': 1.97, 'MN': 1.73,
			'CU': 1.40, 'NI': 1.63}
		DEFAULT_VDW = 2.00
		atoms  = self.data['Atoms']
		coords = self.data['Coordinates']
		ids    = sorted(atoms.keys())
		id_map = {ai: ii for ii, ai in enumerate(ids)}
		n      = len(ids)
		c      = coords[np.array(ids)]
		radii  = np.array([
			VDW.get(atoms[i][1].upper(),DEFAULT_VDW)+probe_radius for i in ids])
		golden = (1 + np.sqrt(5)) / 2
		pts    = np.arange(n_points)
		theta  = np.arccos(1 - 2 * (pts + 0.5) / n_points)
		phi    = 2 * np.pi * pts / golden
		st  = np.sin(theta)
		sph = np.column_stack([st*np.cos(phi), st*np.sin(phi), np.cos(theta)])
		dm  = np.sqrt(((c[:, None, :] - c[None, :, :])**2).sum(2))
		atom_sasa = np.zeros(n)
		for ii in range(n):
			ri       = radii[ii]
			test_pts = c[ii] + ri * sph
			nbr_mask = (dm[ii] < ri + radii) & (dm[ii] > 0)
			nbrs     = np.where(nbr_mask)[0]
			if len(nbrs) == 0:
				atom_sasa[ii] = 4 * np.pi * ri**2
				continue
			diff_pts = (test_pts[:, None, :] - c[nbrs][None, :, :])
			dist_sq  = (diff_pts**2).sum(2)
			r_sq     = radii[nbrs]**2
			buried   = (dist_sq < r_sq[None, :]).any(axis=1)
			n_exp    = int((~buried).sum())
			atom_sasa[ii] = (n_exp / n_points * 4 * np.pi * ri**2)
		for aa_idx, aa_info in self.data['Amino Acids'].items():
			all_atoms = aa_info[2] + aa_info[3]
			sasa = sum(atom_sasa[id_map[a]] for a in all_atoms if a in id_map)
			self.data['Amino Acids'][aa_idx][6] = round(float(sasa), 5)
	def GetDistance(self, res1, atom1, res2, atom2):
		''' Measure distance between any two atoms '''
		A = self.GetAtomCoord(res1, atom1)
		B = self.GetAtomCoord(res2, atom2)
		mag = np.linalg.norm(B - A)
		return mag
	def GetAngle(self, AA1, atom1, AA2, atom2, AA3, atom3):
		''' Measure the angle between three atoms '''
		atom1 = self.GetAtomCoord(AA1, atom1)
		atom2 = self.GetAtomCoord(AA2, atom2)
		atom3 = self.GetAtomCoord(AA3, atom3)
		A = atom2 - atom1
		B = atom2 - atom3
		denom = np.linalg.norm(A) * np.linalg.norm(B)
		if denom < 1e-10: return 0.0
		cos_theta = np.dot(A, B) / denom
		cos_theta = max(-1.0, min(1.0, cos_theta))
		return math.degrees(math.acos(cos_theta))
	def GetAtomBonds(self, index1, index2):
		''' Get the atom pair that participate in a bond from their index '''
		bonds = self.data['Bonds'][index1]
		if index2 not in bonds:
			error = 'Requested two atoms are not bonded'
			raise Exception(error)
		atomA = self.data['Atoms'][index1][0]
		elementA = self.data['Atoms'][index1][1]
		atomB = self.data['Atoms'][index2][0]
		elementB = self.data['Atoms'][index2][1]
		return [atomA, elementA, atomB, elementB]
	def GetIdentity(self, index, item, charge=False):
		''' Identify an atom, atom charge, or amino acid given its index '''
		if item.upper() == 'ATOM':
			Atom = self.data['Atoms'][index]
			if charge: return Atom[2]
			else:      return Atom[0]
		elif item.upper() in ('RESIDUE', 'AMINO ACID'):
			if self.data['Amino Acids'] is None:
				raise Exception(
					'No protein loaded')
			return self.data[
				'Amino Acids'][index][0]
		elif item.upper() in (
		'NUCLEOTIDE', 'DNA', 'RNA'):
			if self.data['Nucleotides'] is None:
				raise Exception(
					'No nucleotide loaded')
			return self.data[
				'Nucleotides'][index][0]
		else:
			raise Exception('Incorrect item')
	def GetAtomCoord(self, res, atom):
		''' Get specific atom coordinates '''
		source = (self.data['Amino Acids']
			or self.data['Nucleotides'])
		info = source[res]
		for i in info[2] + info[3]:
			if self.data['Atoms'][i][0] == atom:
				return self.data['Coordinates'][i]
		raise Exception(
			f'Atom {atom} not found in '
			f'residue {res}')
	def GetAtomIdx(self, res, atom):
		''' Get atom coordinate index by name '''
		source = (self.data['Amino Acids'] or self.data['Nucleotides'])
		info = source[res]
		for i in info[2] + info[3]:
			if self.data['Atoms'][i][0] == atom: return i
		raise Exception(
			f'Atom {atom} not found in '
			f'residue {res}')
	def GetAtomList(self, PDB=False):
		''' Return list of all the atoms '''
		idx = 0 if PDB else 1
		return [x[idx] for x in self.data['Atoms'].values()]
	def GetInfo(self):
		''' Print all basic info about a peptide '''
		print(f"Energy:\t\t\t{self.data['Energy']}")
		print(f"Mass:\t\t\t{self.data['Mass']:,} Da")
		print(f"Rg:\t\t\t{self.data['Rg']} Å")
		for i in self.data['FASTA'].items():
			print(f'Sequence:\t\tChain: {i[0]}\tFASTA: {i[1]}')
		for i in self.data['SS'].items():
			print(f'Secondary Structure:\tChain: {i[0]}\tDSSP: {i[1]}')
		for i in self.data['Size'].items():
			print(f'Size:\t\t\tChain: {i[0]}\tLength: {i[1]}')
	def GetDihedral(self, res, angle_type, chi_type=None):
		''' Get amino acid φ/ψ/ω/χ and nucleotide α/β/γ/δ/ε/ζ/χ dihedrals '''
		at = angle_type.upper()
		mol = self.data['Type']
		prv = self._prevres(res)
		nxt = self._nextres(res)
		gc = self.GetAtomCoord
		if mol == 'Protein':
			if at == 'PHI':
				if prv is None: return 0.0
				r1 = gc(prv, 'C')
				r2 = gc(res, 'N')
				r3 = gc(res, 'CA')
				r4 = gc(res, 'C')
			elif at == 'PSI':
				if nxt is None: return 0.0
				r1 = gc(res, 'N')
				r2 = gc(res, 'CA')
				r3 = gc(res, 'C')
				r4 = gc(nxt, 'N')
			elif at == 'OMEGA':
				if nxt is None: return 180.0
				r1 = gc(res, 'CA')
				r2 = gc(res, 'C')
				r3 = gc(nxt, 'N')
				r4 = gc(nxt, 'CA')
			elif at == 'CHI':
				assert chi_type is not None, \
					'Protein CHI needs chi_type'
				sym = self.data['Amino Acids'][
					res][0].upper()
				ca = self.aminoacids[sym][
					'Chi Angle Atoms'][chi_type-1]
				r1 = gc(res, ca[0])
				r2 = gc(res, ca[1])
				r3 = gc(res, ca[2])
				r4 = gc(res, ca[3])
			else:
				raise Exception(
					f'Unknown protein angle: '
					f'{angle_type}')
		elif mol in ('DNA', 'RNA'):
			if at == 'ALPHA':
				if prv is None: return 0.0
				r1 = gc(prv, "O3'")
				r2 = gc(res, 'P')
				r3 = gc(res, "O5'")
				r4 = gc(res, "C5'")
			elif at == 'BETA':
				r1 = gc(res, 'P')
				r2 = gc(res, "O5'")
				r3 = gc(res, "C5'")
				r4 = gc(res, "C4'")
			elif at == 'GAMMA':
				r1 = gc(res, "O5'")
				r2 = gc(res, "C5'")
				r3 = gc(res, "C4'")
				r4 = gc(res, "C3'")
			elif at == 'DELTA':
				r1 = gc(res, "C5'")
				r2 = gc(res, "C4'")
				r3 = gc(res, "C3'")
				r4 = gc(res, "O3'")
			elif at == 'EPSILON':
				if nxt is None: return 0.0
				r1 = gc(res, "C4'")
				r2 = gc(res, "C3'")
				r3 = gc(res, "O3'")
				r4 = gc(nxt, 'P')
			elif at == 'ZETA':
				if nxt is None: return 0.0
				r1 = gc(res, "C3'")
				r2 = gc(res, "O3'")
				r3 = gc(nxt, 'P')
				r4 = gc(nxt, "O5'")
			elif at == 'CHI':
				tri = self.data['Nucleotides'][res][4]
				ca = self.nucleotides[tri]['Chi Angle Atoms']
				r1 = gc(res, ca[0])
				r2 = gc(res, ca[1])
				r3 = gc(res, ca[2])
				r4 = gc(res, ca[3])
			else:
				raise Exception(
					f'Unknown nucleotide angle'
					f': {angle_type}')
		else:
			raise Exception(
				'No structure loaded. '
				'Call Import() first')
		return self._dihedral(r1, r2, r3, r4)
	def Import(self, filename, chain=None, model=1):
		''' Import Protein/DNA/RNA from .pdb/.cif '''
		if isinstance(chain, str): chain = [chain]
		if chain is not None and not isinstance(chain, list):
			raise Exception(
				f'chain must be None or a list'
				f', got {type(chain).__name__}')
		ext = filename[-3:].upper()
		if ext == 'PDB':   rows = self._parsepdb(filename, chain, model)
		elif ext == 'CIF': rows = self._parsecif(filename, chain, model)
		else:
			raise Exception(
				f'{filename}: unsupported format'
				f' (use .pdb or .cif)')
		if not rows:
			raise Exception(
				f'No ATOM records for chains '
				f'{chain} in {filename}')
		best = {}
		for idx, row in enumerate(rows):
			key = (row[2], row[3], row[0])
			if key not in best or row[7] > rows[best[key]][7]: best[key] = idx
		rows = [rows[i] for i in sorted(best.values())]
		residues = defaultdict(list)
		for row in rows: residues[(row[2], row[3])].append(row)
		resnames = {a[0][1] for a in residues.values()}
		mol = self._detecttype(resnames)
		aa_tri = {v['Tricode'] for v in
			self.aminoacids.values()
			if 'Tricode' in v}
		has_aa = bool(resnames & aa_tri)
		nuc_names = {r for r in resnames
			if r in self.nucleotides
			or r in ('DT', 'T', 'U', 'A', 'G', 'C', 'DA', 'DG', 'DC')}
		has_nuc = bool(nuc_names)
		if has_aa and has_nuc:
			raise Exception(
				f'{filename} contains both '
				f'protein and nucleotide '
				f'residues. Import each '
				f'molecule type separately '
				f'using the chain parameter.')
		self.data = { 'Type': mol, 'Energy': 0, 'Rg': 0, 'Mass': 0, 'Size': {},
			'FASTA': {}, 'SS': {},
			'Nucleotides': {} if mol != 'Protein' else None,
			'Amino Acids': {} if mol == 'Protein' else None,
			'Atoms': {}, 'Bonds': {}, 'Coordinates': np.zeros((0, 3))}
		co = chain if chain is not None else sorted({k[0] for k in residues})
		sk = sorted(residues,
			key=lambda k: (co.index(k[0]) if k[0] in co else 99, k[1]))
		if mol == 'Protein':
			self._importprotein(
				residues, sk, filename, chain)
		else:
			self._importnucleotide(
				residues, sk, mol)
		self._update()
	def Export(self, filename):
		''' Export structure to a .pdb or .cif file '''
		ext = filename[-3:].upper()
		if ext not in ('PDB', 'CIF'):
			raise Exception(
				f'{filename}: unsupported format'
				f' (use .pdb or .cif)')
		src = (self.data['Amino Acids'] or self.data['Nucleotides'])
		if not src:
			raise Exception(
				'No structure loaded. '
				'Call Import() first')
		is_pro = self.data['Type'] == 'Protein'
		ti = 5 if is_pro else 4
		if ext == 'PDB': self._exportpdb(filename, src, ti)
		else: self._exportcif(filename, src, ti)
	def MovePose(self, theta=None, u=None, l=None, ori=None):
		''' Rotate and/or translate the full pose rigidly '''
		coords = self.data['Coordinates'].copy()
		if len(coords) == 0:
			raise Exception('No atoms to move')
		if theta is not None and u is not None:
			u = np.array(u, dtype=float)
			mag = np.linalg.norm(u)
			if mag < 1e-10:
				raise Exception('Rotation axis u cannot be a zero vector')
			u = u / mag
			pivot  = coords.mean(axis=0)
			R      = self._rotmat(theta, u)
			coords = np.matmul(coords - pivot, R) + pivot
		if l is not None and ori is not None:
			ori      = np.array(ori, dtype=float)
			centroid = coords.mean(axis=0)
			d        = ori - centroid
			mag      = np.linalg.norm(d)
			if mag < 1e-10:
				raise Exception(
					'ori coincides with pose centroid — '
					'translation direction is undefined')
			coords = coords + (d / mag) * l
		self.data['Coordinates'] = coords
	def AdjustDistance(self, res1, atom1, res2, atom2, length):
		''' Change distance between two atoms '''
		Ai = self.GetAtomIdx(res1, atom1)
		Bi = self.GetAtomIdx(res2, atom2)
		coords = self.data['Coordinates']
		v = coords[Bi] - coords[Ai]
		mag = np.linalg.norm(v)
		if mag < 1e-10: return
		shift = v * (length / mag) - v
		for idx in self._downstreamatoms(
		res1, atom1, res2, atom2):
			coords[idx] += shift
		self.data['Coordinates'] = coords
	def AdjustAngle(self, res1, atom1, res2, atom2, res3, atom3, theta):
		''' Change angle between three atoms, res2/atom2 is the pivot '''
		A = (self.GetAtomCoord(res3, atom3)- self.GetAtomCoord(res1, atom1))
		B = (self.GetAtomCoord(res3, atom3)- self.GetAtomCoord(res2, atom2))
		u = np.cross(B, A)
		lu = np.linalg.norm(u)
		if lu < 1e-10: return
		u = u / lu
		ori = self.GetAtomCoord(res2, atom2).copy()
		RM = self._rotmat(theta, u)
		coords = self.data['Coordinates']
		for idx in self._downstreamatoms(
		res2, atom2, res3, atom3):
			v = coords[idx] - ori
			coords[idx] = np.matmul(v, RM) + ori
		self.data['Coordinates'] = coords
	def RotateDihedral(self, res, theta, angle_type, chi_type=None):
		''' Set a dihedral angle to theta degrees '''
		pivots = self._dihedralpivots( res, angle_type, chi_type)
		if pivots is None: return
		ra, aa, rb, ab = pivots
		current = self.GetDihedral(res, angle_type, chi_type)
		piv_a = self.GetAtomIdx(ra, aa)
		piv_b = self.GetAtomIdx(rb, ab)
		coords = self.data['Coordinates']
		ori = coords[piv_b].copy()
		u = coords[piv_a] - coords[piv_b]
		mag = np.linalg.norm(u)
		if mag < 1e-10: return
		u = u / mag
		RM_zero = self._rotmat(-current, u)
		RM_new = self._rotmat(theta, u)
		for idx in self._downstreamatoms(
		ra, aa, rb, ab):
			v = coords[idx] - ori
			v = np.matmul(v, RM_zero)
			v = np.matmul(v, RM_new)
			coords[idx] = v + ori
		self.data['Coordinates'] = coords
	def Build(self, sequence, chain='A', fmt='Protein'):
		''' Build protein/DNA/RNA from sequence '''
		fmt = {'protein': 'Protein',
			'dna': 'DNA', 'rna': 'RNA'
			}.get(fmt.lower(), fmt)
		if fmt == 'Protein':
			self._buildprotein(sequence, chain)
		elif fmt in ('DNA', 'RNA'):
			self._buildnucleotide(sequence, fmt)
		else:
			raise Exception(
				f'Unknown format: {fmt}')
		self.CalcCharge()
		if fmt == 'Protein':
			self.CalcSASA()
		self._update()
	def ReBuild(self, sequence=None, D_AA=False, _mutated=None):
		''' Rebuild a structure from internal coords '''
		mol = self.data['Type']
		if mol == 'Protein': self._rebuildprotein(sequence, D_AA)
		elif mol in ('DNA', 'RNA'): self._rebuildnucleotide(sequence, _mutated)
		else:
			raise Exception(
				'No structure loaded. '
				'Call Import() first')
		self._update()
	def Mutate(self, index, residue):
		''' Mutate a residue or nucleotide '''
		mol = self.data['Type']
		if mol == 'Protein':
			AAs = self.data['Amino Acids']
			if index not in AAs:
				raise Exception(
					f'Residue {index} not found')
			ch = AAs[index][1]
			fasta = self.data['FASTA']
			chain_idxs = [i for i in
				sorted(AAs)
				if AAs[i][1] == ch]
			pos = chain_idxs.index(index)
			seq = list(fasta[ch])
			seq[pos] = residue
			new_fasta = dict(fasta)
			new_fasta[ch] = ''.join(seq)
			self.ReBuild(sequence=new_fasta)
		elif mol in ('DNA', 'RNA'):
			nts = self.data['Nucleotides']
			if index not in nts:
				raise Exception(
					f'Nucleotide {index} '
					f'not found')
			fasta = self.data['FASTA']
			first_ch = sorted(
				fasta.keys())[0]
			seq = list(fasta[first_ch])
			N = len(seq)
			seq[index] = residue.upper()
			chains = sorted(set(
				v[1] for v in nts.values()))
			mutated = {index}
			if len(chains) > 1:
				mutated.add(
					2 * N - 1 - index)
			self.ReBuild(
				sequence=''.join(seq),
				_mutated=mutated)
		else:
			raise Exception(
				'No structure loaded. '
				'Call Import() first')
